### PR TITLE
fix: incorrect set HighDeepFreeze flag

### LINKED ISSUE #1977: deep_freeze_peer  flag is available and set to true  on the account_lines  of freeze only enabled account (Version: [20250326091115-develop-f454076f])
Issue exists only on latest commit `f454076fb64e4c0b32d8da86f4512a5f4e151803` of Clio.

## Steps to Reproduce

- Create a trustline for alice and make payment.
- Enable freeze on alice's trustline by issuer.
- Get account_lines response of alice on clio and compare it with rippled response.

Sample request:
```json
{
    "method": "account_lines",
    "params": [
        {
            "account": "rw1KzSTMaR9DkryomMAyNnRhiHHGrdtMCS",
            "ignore_default": false,
            "ledger_index": "validated"
        }
    ]
}
```

## Expected Result
```json
{
    "result": {
        "account": "rw1KzSTMaR9DkryomMAyNnRhiHHGrdtMCS",
        "ledger_hash": "793D429A1D0AE674B62E15158FEECD62117D1560D1BE5399709811837889A60D",
        "ledger_index": 1417786,
        "lines": [
            {
                "account": "rBoHXQ5Ju5dhjrwGtzZ5wN2hSDGwysuHf2",
                "balance": "10000",
                "currency": "USD",
                "freeze_peer": true,
                "limit": "10000",
                "limit_peer": "10000",
                "quality_in": 0,
                "quality_out": 0
            }
        ],
        "status": "success",
        "validated": true
    }
}
```

## Actual Result
```json
{
    "result": {
        "account": "rw1KzSTMaR9DkryomMAyNnRhiHHGrdtMCS",
        "ledger_hash": "F5D5A7676339B2444D434D6E12E066604A983A98FA5868B83B204F049F88A15F",
        "ledger_index": 1417774,
        "validated": true,
        "limit": 200,
        "lines": [
            {
                "account": "rBoHXQ5Ju5dhjrwGtzZ5wN2hSDGwysuHf2",
                "balance": "10000",
                "currency": "USD",
                "limit": "10000",
                "limit_peer": "10000",
                "quality_in": 0,
                "quality_out": 0,
                "freeze_peer": true,
                "deep_freeze_peer": true
            }
        ],
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes #1977

### CODE REVIEW

File: tests/unit/rpc/handlers/AccountLinesTests.cpp [hunk 1]
```diff
@@ -806,6 +807,88 @@ TEST_F(RPCAccountLinesHandlerTest, OptionalResponseField)
...
+                "quality_in": 0,
+                "quality_out": 0,
+                "authorized": true,
+                "freeze": true
+            }
+        ]
+    })";
+
+    auto ledgerHeader = createLedgerHeader(kLEDGER_HASH, 30);
+    ON_CALL(*backend_, fetchLedgerBySequence).WillByDefault(Return(ledgerHeader));
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountLinesTests.cpp]: This can be embedded in the `EXPECT_CALL` below 👍

File: tests/unit/rpc/handlers/AccountLinesTests.cpp [hunk 2]
```diff
@@ -806,6 +807,88 @@ TEST_F(RPCAccountLinesHandlerTest, OptionalResponseField)
...
+    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountLinesTests.cpp]: Please add a line of space before the comment line 🔢

File: tests/unit/rpc/handlers/AccountLinesTests.cpp [hunk 3]
```diff
@@ -806,6 +807,88 @@ TEST_F(RPCAccountLinesHandlerTest, OptionalResponseField)
...
+    auto fake = Blob{'f', 'a', 'k', 'e'};
+
+    // return a non empty account
+    ON_CALL(*backend_, doFetchLedgerObject(accountKk, testing::_, testing::_)).WillByDefault(Return(fake));
+
+    // return owner index
+    ripple::STObject const ownerDir =
+        createOwnerDirLedgerObject({ripple::uint256{kINDEX1}, ripple::uint256{kINDEX2}}, kINDEX1);
+
+    ON_CALL(*backend_, doFetchLedgerObject(owneDirKk, testing::_, testing::_))
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountLinesTests.cpp:860]: Can combine with below line

File: tests/unit/rpc/handlers/AccountLinesTests.cpp [hunk 4]
```diff
@@ -806,6 +807,88 @@ TEST_F(RPCAccountLinesHandlerTest, OptionalResponseField)
...
+    line1.setFlag(ripple::lsfHighAuth);
+    line1.setFlag(ripple::lsfHighFreeze);
+    bbs.push_back(line1.getSerializer().peekData());
+
+    auto line2 = createRippleStateLedgerObject("USD", kACCOUNT2, 20, kACCOUNT, 200, kACCOUNT2, 400, kTXN_ID, 0);
+    line2.setFlag(ripple::lsfLowAuth);
+    line2.setFlag(ripple::lsfLowFreeze);
+    bbs.push_back(line2.getSerializer().peekData());
+
+    ON_CALL(*backend_, doFetchLedgerObjects).WillByDefault(Return(bbs));
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountLinesTests.cpp]: Same here

**Review by godexsoft — CHANGES_REQUESTED** [review]
A few simple changes and we can merge it 👍

File: tests/unit/rpc/handlers/AccountLinesTests.cpp (hunk 3 above)
Comment (PeterChen13579) [reply tests/unit/rpc/handlers/AccountLinesTests.cpp:860]: Realized the line below isn't really needed. I deleted;

**Review by godexsoft — APPROVED** [review]
👍
