### PR TITLE
Remove `full` from ledger RPC forwarding

### LINKED ISSUE #777: Rippled response causes failed forward
UPDATE: we should remove `full` entirely as it's now deprecated. let's also remove `accounts` and any other deprecated fields. See the [doc here](https://xrpl.org/ledger.html#request-format).

-------
Rippled responds slowly for the request 
```
{
    "method": "ledger",
    "params": [
        {
            "ledger_index": "validated",
            "accounts": false,
            "full": true,
            "transactions": false,
            "expand": false,
            "owner_funds": false
        }
    ]
}
```
which causes failed forward. 
Do we need to increase the timeout or give warning for this scenario? @godexsoft

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes #777 

Removes deprecated fields from forwarding proxy.

### CODE REVIEW

**Review by kuznetsss — DISMISSED** [review]
LGTM 👍

File: src/rpc/handlers/Ledger.hpp [hunk 1]
```diff
@@ -102,9 +105,9 @@ class LedgerHandler {
...
     {
         static auto const rpcSpec = RpcSpec{
-            {JS(full), validation::Type<bool>{}, validation::NotSupported{true}},
+            {JS(full), validation::NotSupported{}},
             {JS(full), check::Deprecated{}},
-            {JS(accounts), validation::Type<bool>{}, validation::NotSupported{true}},
+            {JS(accounts), validation::NotSupported{}},
             {JS(accounts), check::Deprecated{}},
             {JS(owner_funds), validation::Type<bool>{}},
             {JS(queue), validation::Type<bool>{}, validation::NotSupported{true}},
```
Comment (kuznetsss) [inline src/rpc/handlers/Ledger.hpp:113]: What about `queue`? You removed it from ForwardingProxy but left value here.

**Review by cindyyan317 — DISMISSED** [review]

File: src/rpc/handlers/Ledger.hpp (hunk 1 above)
Comment (godexsoft) [reply src/rpc/handlers/Ledger.hpp:113]: Thanks for spotting my mistake - i guess i was too enthusiastic about removing stuff :rage4:

**Review by kuznetsss — APPROVED** [review]
