### PR TITLE
fix: Workaround large number validation and parsing

### LINKED ISSUE #2586: Internal error with large limit values (Version: mainnet)
## Issue Description

If I provide a super large `limit` value to Clio in an RPC that accepts a `limit` value, I get an `internal` error. With slightly smaller values, it's a bit more flaky - sometimes I get a ton of results back, and sometimes I get an `internal` error.

I assume this applies to other RPCs that take numbers, but I didn't explore too much.

## Steps to Reproduce

https://xrpl.org/resources/dev-tools/websocket-api-tool?server=wss%3A%2F%2Fs1.ripple.com%2F&req=%7B%20%20%22ledger_hash%22%3A%20%22842B57C1CC0613299A686D3E9F310EC0422C84D3911E5056389AA7E5808A93C8%22%2C%0A%20%20%22command%22%3A%20%22ledger_data%22%2C%0A%20%20%22limit%22%3A%2099999999999%2C%0A%20%20%22binary%22%3A%20true%0A%7D

## Expected Result

Either a clean error or actual responses

## Actual Result

```
{
  "error": "internal",
  "error_code": 73,
  "error_message": "Internal error.",
  "status": "error",
  "type": "response",
  "request": {
    "ledger_hash": "842B57C1CC0613299A686D3E9F310EC0422C84D3911E5056389AA7E5808A93C8",
    "command": "ledger_data",
    "limit": 99999999999,
    "binary": true
  },
  "warnings": [
    {
      "id": 2001,
      "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
    }
  ]
}
```

## Environment

Whatever is currently running on mainnet

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes #2586 

Alternative approach to #2594

### CODE REVIEW

File: src/util/JsonUtils.hpp [hunk 1]
```diff
@@ -86,4 +88,26 @@ removeSecret(boost::json::object const& object)
...
+ * @note This conversion can possibly cause wrapping around or UB. Use with caution.
+ *
+ * @tparam Type The type to cast to
+ * @param value The JSON value to cast
+ * @return Value casted to the requested type
+ * @throws logic_error if the underlying number is neither int64 nor uint64
+ */
+template <std::integral Type>
+Type
+integralValueFrom(boost::json::value const& value)
```
Comment (mathbunnyru) [inline src/util/JsonUtils.hpp]: Maybe call it `integralValueAs`?

File: src/rpc/common/ValidationHelpers.hpp [hunk 2]
```diff
@@ -68,4 +70,58 @@ checkType(boost::json::value const& value)
...
+ * order to avoid Min, Max and other validators throw "not exact" error from Boost.Json library if the value does not
+ * fit in the specified type.
+ *
+ * @tparam Expected The expected type that value should be convertible to
+ * @param value The json value to check the type of
+ * @return true if convertible; false otherwise
+ */
+template <typename Expected>
+[[nodiscard]] static bool
+checkTypeAndClamp(boost::json::value& value)
```
Comment (mathbunnyru) [inline src/rpc/common/ValidationHelpers.hpp:123]: Let's put this function (maybe without `checkType` call) to it's own file and add a test for this function

File: src/rpc/common/ValidationHelpers.hpp [hunk 3]
```diff
@@ -68,4 +70,58 @@ checkType(boost::json::value const& value)
...
+{
+    auto hasError = false;
+
+    if (not checkType<Expected>(value))
+        return false;  // fails basic type check
+
+    if constexpr (std::is_integral_v<Expected> and not std::is_same_v<Expected, bool>) {
+        if constexpr (std::is_unsigned_v<Expected>) {
```
Comment (mathbunnyru) [inline src/rpc/common/ValidationHelpers.hpp]: It would be more readable, if you had 2 functions in impl namespace, one for unsigned, and one for signed

**Review by mathbunnyru — CHANGES_REQUESTED** [review]

File: src/rpc/common/ValidationHelpers.hpp (hunk 2 above)
Comment (godexsoft) [reply src/rpc/common/ValidationHelpers.hpp:123]: Don't think it needs/deserves its own file but will see what tests i can add 👍

File: src/rpc/common/ValidationHelpers.hpp [hunk 4]
```diff
@@ -23,10 +23,49 @@
...
+#include <limits>
 #include <string>
+#include <type_traits>
 
 namespace rpc::validation {
+namespace impl {
+
+template <std::unsigned_integral Expected>
+static void
+clampUnsigned(boost::json::value& value)
```
Comment (kuznetsss) [inline src/rpc/common/ValidationHelpers.hpp]: Maybe `clampSigned` and `clampUnsigned` could be named both as `clamp`? I think compiler should be able to resolve it.

**Review by kuznetsss — DISMISSED** [review]

File: src/rpc/common/ValidationHelpers.hpp (hunk 4 above)
Comment (godexsoft) [reply src/rpc/common/ValidationHelpers.hpp]: Yeah you are right. Good call 👍

File: src/rpc/common/ValidationHelpers.hpp [hunk 5]
```diff
@@ -23,10 +23,49 @@
...
 #include <cstdint>
+#include <limits>
 #include <string>
+#include <type_traits>
 
 namespace rpc::validation {
+namespace impl {
+
+template <std::unsigned_integral Expected>
+static void
```
Comment (mathbunnyru) [inline src/rpc/common/ValidationHelpers.hpp]: static is not needed here (and below)

File: src/rpc/common/ValidationHelpers.hpp [hunk 6]
```diff
@@ -23,10 +23,49 @@
...
 #include <boost/json/value.hpp>
 
+#include <concepts>
 #include <cstdint>
+#include <limits>
 #include <string>
+#include <type_traits>
 
 namespace rpc::validation {
+namespace impl {
```
Comment (mathbunnyru) [inline src/rpc/common/ValidationHelpers.hpp:33]: nit: empty line between

File: src/rpc/common/ValidationHelpers.hpp (hunk 2 above)
Comment (mathbunnyru) [reply src/rpc/common/ValidationHelpers.hpp:123]: Ok

File: src/rpc/common/Validators.hpp [hunk 7]
```diff
@@ -148,13 +148,13 @@ struct Type final {
      * @return `RippledError::rpcINVALID_PARAMS` if validation failed; otherwise no error is returned
      */
     [[nodiscard]] MaybeError
-    verify(boost::json::value const& value, std::string_view key) const
+    verify(boost::json::value& value, std::string_view key) const
```
Comment (mathbunnyru) [inline src/rpc/common/Validators.hpp:153]: Don't we want to name it `verifyAndClamp` or sth like that?

Comment (godexsoft) [reply src/rpc/common/Validators.hpp:153]: No, this is supposed to be used with only validators (non-modifying) but we make the exception for clamping ints because we had to. Let's not introduce unnecessary changes

File: src/rpc/common/ValidationHelpers.hpp (hunk 6 above)
Comment (godexsoft) [reply src/rpc/common/ValidationHelpers.hpp:33]: Why? while we have a few examples with a space line between, most cases are like this without the space. Frankly i think this is one place where the empty line does not make it better

Comment (mathbunnyru) [reply src/rpc/common/ValidationHelpers.hpp:33]: Because you have some code after `impl` closes, and it doesn't look symmetrical

Comment (mathbunnyru) [reply src/rpc/common/ValidationHelpers.hpp:33]: Not a big deal at all, you can leave it as it is right now :)

File: src/rpc/common/Validators.hpp (hunk 7 above)
Comment (mathbunnyru) [reply src/rpc/common/Validators.hpp:153]: Maybe let's add a comment here why we (possibly) modify value?

File: src/rpc/common/ValidationHelpers.hpp (hunk 5 above)
Comment (godexsoft) [reply src/rpc/common/ValidationHelpers.hpp]: Yeah i agree, result of copypasta 👍

File: src/rpc/common/ValidationHelpers.hpp (hunk 6 above)
Comment (godexsoft) [reply src/rpc/common/ValidationHelpers.hpp:33]: Nah i like to fix it, so now all examples with extra line are gone 😝

**Review by mathbunnyru — DISMISSED** [review]

**Review by mathbunnyru — APPROVED** [review]
