### PR TITLE
fix: Add MPT to txn JSON

### LINKED ISSUE #2332: Add MPT related txns into issuer's AccountTx RPC
## Issue Description

Rippled PR: https://github.com/XRPLF/rippled/commit/b8626ea3c66b05ed754f62ae89e46f3a0d91dcb3

## Steps to Reproduce

Sample request:
```
{
    "method": "account_tx",
    "params": [
        {
            "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ"
        }
    ]
}
```

## Expected Result

Rippled response:
```
{
    "result": {
        "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
        "ledger_index_max": 4465482,
        "ledger_index_min": 4464490,
        "limit": 0,
        "status": "success",
        "transactions": [
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Flags": 0,
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "OutstandingAmount": "10000",
                                    "OwnerNode": "0",
                                    "Sequence": 4465445
                                },
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "PreviousFields": {
                                    "OutstandingAmount": "0"
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999800",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465447
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "39999900",
                                    "Sequence": 4465446
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Flags": 0,
                                    "MPTAmount": "10000",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                                    "OwnerNode": "0"
                                },
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "PreviousFields": {},
                                "PreviousTxnID": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                                "PreviousTxnLgrSeq": 4465451
                            }
                        }
                    ],
                    "TransactionIndex": 5,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    }
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "DeliverMax": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "Destination": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "Sequence": 4465446,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "Payment",
                    "TxnSignature": "3044022041AAB1103CC12594B8CEBFCDCE00DE79BCCB4CBAE5783FA5A15F8A22ACA6110F022008E6235A58090EFAEDE873C7F67E9635622915ADD66DF645ECE0544CFE0D998A",
                    "ctid": "C044232D00050002",
                    "date": 805830251,
                    "hash": "C51EFC6ED34E7B33B13FAA425383AEBEC4F2BDBB6DAEFDDBBABC051D862B66BA",
                    "inLedger": 4465453,
                    "ledger_index": 4465453
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465450
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "95B3155BF1D65091FC248D913FD8E4AB03013DD6DC3EC3F834C6DB9F40D8F248",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465449
                                },
                                "PreviousTxnID": "2B63151BCB3D8DCD4837331A072E91F1DDFBB24A0CFC9317624DE87A16B0C2CE",
                                "PreviousTxnLgrSeq": 4465449
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "NewFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                                }
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "D333D883E263D617335A97F102869EFEBAB9945294FACF746E8D85EB079B2611",
                                "NewFields": {
                                    "Owner": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "RootIndex": "D333D883E263D617335A97F102869EFEBAB9945294FACF746E8D85EB079B2611"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 15,
                    "TransactionResult": "tesSUCCESS"
                },
                "tx": {
                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                    "Sequence": 4465449,
                    "SigningPubKey": "02FD485E8014F7B63964645E6B7D1459EE992299D62931D8A08DDA37EE6A4CA597",
                    "TransactionType": "MPTokenAuthorize",
                    "TxnSignature": "3044022041828EDC333C633284577586D8E373AF21D4C525FB17A1F4917E623F74A996A4022009FC6E830E6FB3F8D9052F7AC97F648FB2E20DFEBA8D1A3487BC507B702A4B05",
                    "ctid": "C044232B000F0002",
                    "date": 805830243,
                    "hash": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                    "inLedger": 4465451,
                    "ledger_index": 4465451
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "NewFields": {
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465446
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465445
                                },
                                "PreviousTxnID": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                                "PreviousTxnLgrSeq": 4465445
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B",
                                "NewFields": {
                                    "Owner": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "RootIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 12,
                    "TransactionResult": "tesSUCCESS",
                    "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465445,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "MPTokenIssuanceCreate",
                    "TxnSignature": "3045022100B7330D8C22ECC4ABF12306829FAE9145382949240D41E5822C0263482C1B9CFE02200AA4FB6A4E0549E0419B53D1F0AEFC5D70E0B7CB05B76DF8BCD8DDE761DAF23A",
                    "ctid": "C0442327000C0002",
                    "date": 805830231,
                    "hash": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                    "inLedger": 4465447,
                    "ledger_index": 4465447
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "NewFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "40000000",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                                    "Balance": "99799999500",
                                    "Flags": 0,
                                    "OwnerCount": 0,
                                    "Sequence": 4465436
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "E30641084BA9892565B5FD310BFB123CDD3C084301F7A44A119FAEF28684900B",
                                "PreviousFields": {
                                    "Balance": "99839999600",
                                    "Sequence": 4465435
                                },
                                "PreviousTxnID": "EB16466C1A88E4DE46F45C827CF0BC459CE322A54318AF9184177F5D58EE503D",
                                "PreviousTxnLgrSeq": 4465441
                            }
                        }
                    ],
                    "TransactionIndex": 1,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": "40000000"
                },
                "tx": {
                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                    "Amount": "40000000",
                    "DeliverMax": "40000000",
                    "Destination": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465435,
                    "SigningPubKey": "0248B7B2CFFCF2FEF8A58F4E9CE5CBE52C9C66C2E89B6B79262FCD5AC182C63550",
                    "TransactionType": "Payment",
                    "TxnSignature": "304402206E6C43ED15F19791AA185565FBC3EAE9AD03B98D5D59A66FD2D2C8202E11A0DF022032AE14C8BC67F7DAEF6A1252519E34CB6B369519E09A079D32456BE7033A1B54",
                    "ctid": "C044232500010002",
                    "date": 805830222,
                    "hash": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                    "inLedger": 4465445,
                    "ledger_index": 4465445
                },
                "validated": true
            }
        ],
        "validated": true
    }
}
```

## Actual Result

Clio response:

```
{
    "result": {
        "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
        "ledger_index_min": 4465121,
        "ledger_index_max": 4465490,
        "transactions": [
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Flags": 0,
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "OutstandingAmount": "10000",
                                    "OwnerNode": "0",
                                    "Sequence": 4465445
                                },
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "PreviousFields": {
                                    "OutstandingAmount": "0"
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999800",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465447
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "39999900",
                                    "Sequence": 4465446
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Flags": 0,
                                    "MPTAmount": "10000",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                                    "OwnerNode": "0"
                                },
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "PreviousFields": {},
                                "PreviousTxnID": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                                "PreviousTxnLgrSeq": 4465451
                            }
                        }
                    ],
                    "TransactionIndex": 5,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    }
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "Destination": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "Sequence": 4465446,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "Payment",
                    "TxnSignature": "3044022041AAB1103CC12594B8CEBFCDCE00DE79BCCB4CBAE5783FA5A15F8A22ACA6110F022008E6235A58090EFAEDE873C7F67E9635622915ADD66DF645ECE0544CFE0D998A",
                    "hash": "C51EFC6ED34E7B33B13FAA425383AEBEC4F2BDBB6DAEFDDBBABC051D862B66BA",
                    "DeliverMax": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "ctid": "C044232D00050002",
                    "date": 805830251,
                    "ledger_index": 4465453,
                    "inLedger": 4465453
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "NewFields": {
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465446
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465445
                                },
                                "PreviousTxnID": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                                "PreviousTxnLgrSeq": 4465445
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B",
                                "NewFields": {
                                    "Owner": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "RootIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 12,
                    "TransactionResult": "tesSUCCESS",
                    "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465445,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "MPTokenIssuanceCreate",
                    "TxnSignature": "3045022100B7330D8C22ECC4ABF12306829FAE9145382949240D41E5822C0263482C1B9CFE02200AA4FB6A4E0549E0419B53D1F0AEFC5D70E0B7CB05B76DF8BCD8DDE761DAF23A",
                    "hash": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                    "ctid": "C0442327000C0002",
                    "date": 805830231,
                    "ledger_index": 4465447,
                    "inLedger": 4465447
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "NewFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "40000000",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                                    "Balance": "99799999500",
                                    "Flags": 0,
                                    "OwnerCount": 0,
                                    "Sequence": 4465436
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "E30641084BA9892565B5FD310BFB123CDD3C084301F7A44A119FAEF28684900B",
                                "PreviousFields": {
                                    "Balance": "99839999600",
                                    "Sequence": 4465435
                                },
                                "PreviousTxnID": "EB16466C1A88E4DE46F45C827CF0BC459CE322A54318AF9184177F5D58EE503D",
                                "PreviousTxnLgrSeq": 4465441
                            }
                        }
                    ],
                    "TransactionIndex": 1,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": "40000000"
                },
                "tx": {
                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                    "Amount": "40000000",
                    "Destination": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465435,
                    "SigningPubKey": "0248B7B2CFFCF2FEF8A58F4E9CE5CBE52C9C66C2E89B6B79262FCD5AC182C63550",
                    "TransactionType": "Payment",
                    "TxnSignature": "304402206E6C43ED15F19791AA185565FBC3EAE9AD03B98D5D59A66FD2D2C8202E11A0DF022032AE14C8BC67F7DAEF6A1252519E34CB6B369519E09A079D32456BE7033A1B54",
                    "hash": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                    "DeliverMax": "40000000",
                    "ctid": "C044232500010002",
                    "date": 805830222,
                    "ledger_index": 4465445,
                    "inLedger": 4465445
                },
                "validated": true
            }
        ],
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes #2332

### CODE REVIEW

File: src/feed/impl/TransactionFeed.cpp [hunk 1]
```diff
@@ -205,7 +205,7 @@ TransactionFeed::pub(
         pubObj[JS(meta)] = rpc::toJson(*meta);
         rpc::insertDeliveredAmount(pubObj[JS(meta)].as_object(), tx, meta, txMeta.date);
         rpc::insertDeliverMaxAlias(pubObj[txKey].as_object(), version);
-        rpc::insertMPTIssuanceID(pubObj[JS(meta)].as_object(), tx, meta);
+        rpc::insertMPTIssuanceID(pubObj[txKey].as_object(), meta);
```
Comment (kuznetsss) [inline src/feed/impl/TransactionFeed.cpp]: Maybe you could save `pubObj[txKey].as_object()` into a variable and use it in two places?

File: tests/common/util/TestObject.cpp [hunk 2]
```diff
@@ -1499,6 +1499,58 @@ createMpTokenObject(std::string_view accountId, ripple::uint192 issuanceID, std:
...
+    tx.setFieldAmount(ripple::sfFee, ripple::STAmount(fee, false));
+    tx.setFieldU32(ripple::sfSequence, seq);
+    char const* key = "test";
+    ripple::Slice const slice(key, 4);
+    tx.setFieldVL(ripple::sfSigningPubKey, slice);
+    return tx;
+}
+
+data::TransactionAndMetadata
+createMPTIssuanceCreateTxWithMetadata(std::string_view accountId, uint32_t seq, uint32_t fee)
```
Comment (godexsoft) [inline tests/common/util/TestObject.cpp]: In ideal world `seq` and `fee` should be strong types but since this is a test thing please at least keep the order they appear consistent, otherwise it's a disaster waiting to happen 🔢

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 3]
```diff
@@ -55,6 +56,7 @@ constexpr auto kNFT_ID = "05FB0EB4B899F056FA095537C5817163801F544BAFCEA39C995D76
 constexpr auto kNFT_ID2 = "05FB0EB4B899F056FA095537C5817163801F544BAFCEA39C995D76DB4D16F9DA";
 constexpr auto kNFT_ID3 = "15FB0EB4B899F056FA095537C5817163801F544BAFCEA39C995D76DB4D16F9DF";
 constexpr auto kINDEX = "E6DBAFC99223B42257915A63DFC6B0C032D4070F9A574B255AD97466726FC322";
+constexpr auto const kMPT_ISSUANCE_ID = "000000014B4E9C06F24296074F7BC48F92A97916C6DC5EA9";
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: `constexpr` is implicitly `const` so `const` can be omitted

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 4]
```diff
@@ -1657,6 +1659,99 @@ TEST_F(RPCAccountTxHandlerTest, NFTTxs_API_v2)
...
+    EXPECT_CALL(*backend_, fetchAccountTransactions).Times(1);
+
+    auto const ledgerHeader = createLedgerHeader(kLEDGER_HASH, kMIN_SEQ + 1);
+    EXPECT_CALL(*backend_, fetchLedgerBySequence(kMIN_SEQ + 1, _)).WillOnce(Return(ledgerHeader));
+
+    runSpawn([&, this](auto yield) {
+        auto const handler = AnyHandler{AccountTxHandler{backend_, mockETLServicePtr_}};
+        static auto const kINPUT = json::parse(
+            fmt::format(
+                R"JSON({{
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountTxTests.cpp:1674]: nit: Strange formatting here 🔢

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 5]
```diff
@@ -1657,6 +1659,99 @@ TEST_F(RPCAccountTxHandlerTest, NFTTxs_API_v2)
...
+        kACCOUNT,
+        kMPT_ISSUANCE_ID
+    );
+
+    auto mptTx = createMPTIssuanceCreateTxWithMetadata(kACCOUNT, 1, 50);
+    mptTx.ledgerSequence = kMIN_SEQ + 1;
+    mptTx.date = 1;
+
+    auto transactions = std::vector<TransactionAndMetadata>{std::move(mptTx)};
+    auto const transCursor = TransactionsAndCursor{.txns = transactions, .cursor = std::nullopt};
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: Looks like we only use `transactions` here - let's `std::move` it

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 6]
```diff
@@ -1657,6 +1659,99 @@ TEST_F(RPCAccountTxHandlerTest, NFTTxs_API_v2)
...
+
+    ON_CALL(*backend_, fetchAccountTransactions).WillByDefault(Return(transCursor));
+    EXPECT_CALL(*backend_, fetchAccountTransactions).Times(1);
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: `.Times(1)` is the default IIRC

File: tests/common/util/TestObject.cpp [hunk 7]
```diff
@@ -1499,6 +1499,58 @@ createMpTokenObject(std::string_view accountId, ripple::uint192 issuanceID, std:
...
+ripple::STObject
+createMPTIssuanceCreateTx(std::string_view accountId, uint32_t fee, uint32_t seq)
+{
+    ripple::STObject tx(ripple::sfTransaction);
+    tx.setFieldU16(ripple::sfTransactionType, ripple::ttMPTOKEN_ISSUANCE_CREATE);
+    tx.setAccountID(ripple::sfAccount, getAccountIdWithString(accountId));
+    tx.setFieldAmount(ripple::sfFee, ripple::STAmount(fee, false));
+    tx.setFieldU32(ripple::sfSequence, seq);
+    char const* key = "test";
+    ripple::Slice const slice(key, 4);
```
Comment (godexsoft) [inline tests/common/util/TestObject.cpp]: nit: The key can probably be the literal `"test"` itself? Probably no need for a variable here

File: src/rpc/RPCHelpers.cpp [hunk 8]
```diff
@@ -347,14 +347,15 @@ getMPTIssuanceID(std::shared_ptr<ripple::TxMeta const> const& meta)
...
  * @param meta The metadata
  * @return true if the transaction can have a mpt_issuance_id
  */
 static bool
-canHaveMPTIssuanceID(std::shared_ptr<ripple::STTx const> const& txn, std::shared_ptr<ripple::TxMeta const> const& meta)
+canHaveMPTIssuanceID(boost::json::object const& txnJson, std::shared_ptr<ripple::TxMeta const> const& meta)
 {
-    if (txn->getTxnType() != ripple::ttMPTOKEN_ISSUANCE_CREATE)
+    if (txnJson.at(JS(TransactionType)).is_string() and
+        txnJson.at(JS(TransactionType)).as_string() != JS(MPTokenIssuanceCreate))
```
Comment (godexsoft) [inline src/rpc/RPCHelpers.cpp]: Is this string guaranteed to be in this specific casing or can it somehow come through as lower case or something else in reality? Perhaps `boost::iequals` would be safer here in case we are not 100% sure

**Review by godexsoft — CHANGES_REQUESTED** [review]

File: tests/common/util/TestObject.cpp [hunk 9]
```diff
@@ -820,8 +817,7 @@ createNftModifyTxWithMetadata(std::string_view accountId, std::string_view nftID
     tx.setFieldAmount(ripple::sfFee, amount);
     tx.setFieldH256(ripple::sfNFTokenID, ripple::uint256{nftID});
     tx.setFieldU32(ripple::sfSequence, 100);
-    char const* key = "test";
-    ripple::Slice const slice(key, 4);
+    ripple::Slice const slice("key", 4);
```
Comment (kuznetsss) [inline tests/common/util/TestObject.cpp]: It was `test` here.

File: tests/common/util/TestObject.cpp [hunk 10]
```diff
@@ -1172,8 +1163,7 @@ createCreateNftOfferTxWithMetadata(
     tx.setFieldAmount(ripple::sfAmount, price);
     tx.setFieldU32(ripple::sfSequence, seq);
     tx.setFieldH256(ripple::sfNFTokenID, ripple::uint256{nftId});
-    char const* key = "test";
-    ripple::Slice const slice(key, 4);
+    ripple::Slice const slice("test", 4);
```
Comment (kuznetsss) [inline tests/common/util/TestObject.cpp]: Maybe create `static ripple::Slice const` object?

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 11]
```diff
@@ -907,7 +909,7 @@ TEST_F(RPCAccountTxHandlerTest, SpecificLedgerIndex)
     );
 
     auto const ledgerHeader = createLedgerHeader(kLEDGER_HASH, kMAX_SEQ - 1);
-    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
+    EXPECT_CALL(*backend_, fetchLedgerBySequence);
```
Comment (kuznetsss) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: You could merge it with `ON_CALL()`.

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 12]
```diff
@@ -1599,6 +1600,99 @@ TEST_F(RPCAccountTxHandlerTest, NFTTxs_API_v2)
...
+
+    auto mptTx = createMPTIssuanceCreateTxWithMetadata(kACCOUNT, 50, 1);
+    mptTx.ledgerSequence = kMIN_SEQ + 1;
+    mptTx.date = 1;
+
+    auto transactions = std::vector<TransactionAndMetadata>{std::move(mptTx)};
+    auto const transCursor = TransactionsAndCursor{.txns = std::move(transactions), .cursor = std::nullopt};
+
+    ON_CALL(*backend_, fetchAccountTransactions).WillByDefault(Return(transCursor));
+    EXPECT_CALL(*backend_, fetchAccountTransactions);
```
Comment (kuznetsss) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: Could use `EXPECT_CALL().WillOnce()`.

File: tests/unit/rpc/handlers/AccountTxTests.cpp [hunk 13]
```diff
@@ -909,9 +909,7 @@ TEST_F(RPCAccountTxHandlerTest, SpecificLedgerIndex)
     );
 
     auto const ledgerHeader = createLedgerHeader(kLEDGER_HASH, kMAX_SEQ - 1);
-    EXPECT_CALL(*backend_, fetchLedgerBySequence);
-    ON_CALL(*backend_, fetchLedgerBySequence(kMAX_SEQ - 1, _)).WillByDefault(Return(ledgerHeader));
-
+    EXPECT_CALL(*backend_, fetchLedgerBySequence(kMAX_SEQ - 1, _)).WillRepeatedly(Return(ledgerHeader));
```
Comment (kuznetsss) [inline tests/unit/rpc/handlers/AccountTxTests.cpp]: Shouldn't it be `WillOnce()` because we were expecting it to be called one time? (Here and in multiple places below)

Comment (PeterChen13579) [reply tests/unit/rpc/handlers/AccountTxTests.cpp]: mb, yea you're right 👍

**Review by kuznetsss — APPROVED** [review]
👍
