### PR TITLE
style: Fix clang-tidy issue

### LINKED ISSUE #1569: Clang-tidy found bugs in code 🐛
Clang-tidy found issues in the code:
List of the issues found: https://github.com/XRPLF/clio/actions/runs/10158133954/

### LINKED ISSUE #1573: Clang-tidy found bugs in code 🐛
Clang-tidy found issues in the code:
List of the issues found: https://github.com/XRPLF/clio/actions/runs/10175119953/

### PR DESCRIPTION
**Pull request by kuznetsss**
Fixes #1569. Fixes #1573.

### CODE REVIEW

File: tests/unit/rpc/handlers/LedgerEntryTests.cpp [hunk 1]
```diff
@@ -2950,7 +2950,7 @@ TEST_F(RPCLedgerEntryDeathTest, RangeNotAvailable)
 {
     boost::asio::io_context ctx;
     bool checkCalled = false;
-    spawn(ctx, [&, _ = make_work_guard(ctx)](boost::asio::yield_context yield) {
+    spawn(ctx, [&, _unused = make_work_guard(ctx)](boost::asio::yield_context yield) {
```
Comment (cindyyan317) [inline tests/unit/rpc/handlers/LedgerEntryTests.cpp:2953]: one _ is not okay, but two _ (line 2963) is okay?

**Review by cindyyan317 — APPROVED** [review]

File: tests/unit/rpc/handlers/LedgerEntryTests.cpp (hunk 1 above)
Comment (kuznetsss) [reply tests/unit/rpc/handlers/LedgerEntryTests.cpp:2953]: Yeah, I tried to use `__` here but clang told me that it shadows a defined symbol. So I don't understand why it is allowed there
