### PR TITLE
fix: Print out error details of web context

### LINKED ISSUE #1698: [bug] Clio fails to print out error detail
## Issue Description
Fails to print out error detail:
 https://github.com/XRPLF/clio/blob/develop/src/web/RPCServerHandler.hpp#L184 is supposed to print out detail of error. However, we saw 
```
clio_2024-10-14_15-35-31.log:2024-10-14 14:06:47.680487 [0x00007f83ccff9700] RPC:WRN [47299129] Could not create Web context: true
```
in log. Not too much information.
## Expected Result
Print out error detail

### PR DESCRIPTION
**Pull request by emreariyurek**
Fix https://github.com/XRPLF/clio/issues/1698

### CODE REVIEW

File: src/rpc/Factories.cpp [hunk 1]
```diff
@@ -85,13 +85,13 @@ makeHttpContext(
 )
 {
     if (!request.contains("method"))
-        return Error{{ClioError::RpcCommandIsMissing}};
+        return Error{{ClioError::RpcCommandIsMissing, "Method is not specified."}};
```
Comment (godexsoft) [inline src/rpc/Factories.cpp]: The messages are already in `Errors.cpp` and should not need to be added here or below

**Review by godexsoft — CHANGES_REQUESTED** [review]
Thanks for the proposed changes 👍 I think it should work without adding custom messages. Please try🥇

File: src/rpc/Factories.cpp (hunk 1 above)
Comment (godexsoft) [reply src/rpc/Factories.cpp]: @emreariyurek do you still want to fix it?

Comment (emreariyurek) [reply src/rpc/Factories.cpp]: Hello @godexsoft, yes, I'll update it. I didn't have a chance to look at it last week as I was on vacation. Thank you for reminding me, I hadn't noticed getErrorInfo function

File: src/rpc/Errors.cpp [hunk 2]
```diff
@@ -39,6 +39,17 @@ using namespace std;
 
 namespace rpc {
 
+std::ostream&
+operator<<(std::ostream& stream, Status const& status)
+{
+    if (!status.message.empty())
+        stream << status.message;
+    else if (auto const clioCode = std::get_if<ClioError>(&status.code))
+        stream << std::string{getErrorInfo(*clioCode).message};
```
Comment (godexsoft) [inline src/rpc/Errors.cpp]: Please also do it for `RippledError`.

**Review by godexsoft — CHANGES_REQUESTED** [review]

File: src/rpc/Errors.cpp (hunk 2 above)
Comment (kuznetsss) [reply src/rpc/Errors.cpp]: We should print here all the fields if they are presented:
- `code` for all variants (please use `util::OverloadSet` for this)
- `error` if it's not empty
- `message` if it's not empty
- `extraInfo` if it's not `nullopt`

Comment (emreariyurek) [reply src/rpc/Errors.cpp]: Thank you for the feedback! Updates are done - feel free to take another look when you have a chance, and let me know if there’s anything else I can improve

**Comment by kuznetsss** [comment]
Hi @emreariyurek, changes look good, but could you please add unit tests for `Error::operator<<()`?

File: tests/unit/rpc/ErrorTests.cpp [hunk 3]
```diff
@@ -189,3 +189,66 @@ TEST(RPCErrorsTest, InvalidWarningToJSON)
     };
     EXPECT_ANY_THROW((void)notSanitizedMakeWarning());
 }
+
+struct StatusStreamTestBundle {
+    rpc::Status status;
```
Comment (kuznetsss) [inline tests/unit/rpc/ErrorTests.cpp:196]: Please add test name here and use [TestNameGenerator](https://github.com/XRPLF/clio/blob/develop/tests/common/util/NameGenerator.hpp#L24) in `INSTANTIATE_TEST_SUITE_P()`.

Comment (emreariyurek) [reply tests/unit/rpc/ErrorTests.cpp:196]: done

**Review by kuznetsss — DISMISSED** [review]
LGTM, thanks!

File: src/rpc/Errors.cpp [hunk 4]
```diff
@@ -39,6 +39,39 @@ using namespace std;
...
+                    stream << ", Message: " << ripple::RPC::get_error_info(err).message;
+            },
+            [&stream, &status](ClioError err) {
+                stream << "Code: " << static_cast<std::underlying_type_t<ClioError>>(err);
+                if (!status.error.empty())
+                    stream << ", Error: " << status.error;
+                if (!status.message.empty())
+                    stream << ", Message: " << status.message;
+                else
+                    stream << ", Message: " << std::string{getErrorInfo(err).message};
```
Comment (mathbunnyru) [inline src/rpc/Errors.cpp]: If it's a string_view, I think you can output it directly here

File: src/rpc/Errors.cpp [hunk 5]
```diff
@@ -39,6 +39,39 @@ using namespace std;
...
+            }
+        },
+        status.code
+    );
+
+    if (status.extraInfo)
+        stream << ", Extra Info: " << status.extraInfo.value();
```
Comment (mathbunnyru) [inline src/rpc/Errors.cpp]:
```suggestion
    if (status.extraInfo.has_value())
        stream << ", Extra Info: " << *status.extraInfo;
```

**Review by mathbunnyru — APPROVED** [review]

**Review by godexsoft — APPROVED** [review]
Nice 👍
