### PR TITLE
fix: Better errors on logger init failure

### LINKED ISSUE #1326: Crash with existing file path in `log_directory` (Version: 2.1.1)
## Issue Description

If an existing **_file_** path is added in "log_directory" of Clio config and start running Clio then Clio is throwing an exception and then crashing.

## Steps to Reproduce

enable "log_directory" in Clio config with the path of an existing file

## Expected Result

Throw an exception and stop running Clio

## Actual Result

Throw an exception and then Clio is crashing

## Environment

Reproducible in linux and Mac irrespective of Clio version.

## Supporting Files

```
2024-04-05 08:50:02.560962 (util/log/Logger.h:265) [0x00000001fb4c3ac0] General:FTL Exit on exception: boost::filesystem::create_directories: File exists [system:17]: "/file/path/clio_log", "/file/path/clio_log"

2024-04-05 08:50:02.563254 (util/log/Logger.h:265) [0x00000001fb4c3ac0] General:FTL Exit on terminate. Backtrace:
 0# util::(anonymous namespace)::terminationHandler() in /path/of/clio/build/clio_server

 1# 0x000000019376D0F4 in /usr/lib/libc++abi.dylib
 2# 0x00000001937705F8 in /usr/lib/libc++abi.dylib
 3# boost::log::v2s_mt_posix::aux::lazy_singleton<boost::log::v2s_mt_posix::core::implementation, boost::shared_ptr<boost::log::v2s_mt_posix::core>>::get() in /path/of/clio/build/clio_server
 4# util::Logger::Pump::~Pump() in /path/of/clio/build/clio_server
 5# std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread>>::~vector[abi:v160006]() in /path/of/clio/build/clio_server
2024-04-05 08:50:02.596899 (util/log/Logger.h:265) [0x00000001fb4c3ac0] General:FTL Exit on terminate. Can't get backtrace.
libc++abi: terminate_handler unexpectedly threw an exception
```

### PR DESCRIPTION
**Pull request by kuznetsss**
Fixes #1326.

### CODE REVIEW

File: tests/unit/LoggerTests.cpp [hunk 1]
```diff
@@ -175,6 +177,28 @@ TEST_F(LoggerInitTest, ChannelLogLevel)
     }
 }
 
+TEST_F(LoggerInitTest, InitReturnsErrorIfCouldNotCreateLogDirectory)
+{
+    auto const parsingErrors = config_.parse(ConfigFileJson{boost::json::object{{"log_directory", "/root"}}});
```
Comment (godexsoft) [inline tests/unit/LoggerTests.cpp]: `/root` might be writeable in CI, no? I'd try something like `/dev` or similar

**Review by godexsoft — CHANGES_REQUESTED** [review]
Lovely! Just please check the `/root` path in the test and let's get this merged 👍

**Review by cindyyan317 — DISMISSED** [review]
👍

File: src/util/log/Logger.cpp [hunk 2]
```diff
@@ -175,8 +175,9 @@ LogService::init(config::ClioConfigDefinition const& config)
     for (auto it = overrides.begin<util::config::ObjectView>(); it != overrides.end<util::config::ObjectView>(); ++it) {
         auto const& channelConfig = *it;
         auto const name = channelConfig.get<std::string>("channel");
-        if (std::count(std::begin(Logger::kCHANNELS), std::end(Logger::kCHANNELS), name) == 0)
+        if (std::count(std::begin(Logger::kCHANNELS), std::end(Logger::kCHANNELS), name) == 0) {
```
Comment (godexsoft) [inline src/util/log/Logger.cpp]: Let's use `ranges::contains` instead?

File: tests/unit/LoggerTests.cpp [hunk 3]
```diff
@@ -179,7 +179,7 @@ TEST_F(LoggerInitTest, ChannelLogLevel)
 
 TEST_F(LoggerInitTest, InitReturnsErrorIfCouldNotCreateLogDirectory)
 {
-    auto const parsingErrors = config_.parse(ConfigFileJson{boost::json::object{{"log_directory", "/root"}}});
+    auto const parsingErrors = config_.parse(ConfigFileJson{boost::json::object{{"log_directory", "/proc/logs"}}});
```
Comment (godexsoft) [inline tests/unit/LoggerTests.cpp:183]: Worth adding a comment why `/proc/logs` was chosen. Something about it being always readonly i guess.

File: tests/unit/LoggerTests.cpp [hunk 4]
```diff
@@ -189,9 +189,18 @@ TEST_F(LoggerInitTest, InitReturnsErrorIfCouldNotCreateLogDirectory)
...
+    {
+        "log_channels": [
+            {
+                "channel": "SomeChannel",
+                "log_level": "warn"
+            }
+        ]
+    })json";
+
+    auto json = boost::json::parse(jsonStr).as_object();
```
Comment (godexsoft) [inline tests/unit/LoggerTests.cpp]: Can this be `const` since we don't move it?

**Review by godexsoft — CHANGES_REQUESTED** [review]
A few more small improvements spotted. Nothing major or blocking though 👍

**Review by godexsoft — DISMISSED** [review]
🚀

**Review by godexsoft — APPROVED** [review]
