### PR TITLE
fix: Empty signer list

### LINKED ISSUE #2730: Empty signer_lists field missing in response (Version: 2.6.0)
## Issue Description

Issue shared from Mattermost:
> looks like clio has braking change and do not return empty signer lists in response anymore

## Reproduction Steps

if I send request like this, then there is no signer_lists on any response, in case it is empty
```
{
    "command": "account_info",
    "account": "rsuUjfWxrACCAwGQDsNeZUhpzXf1n1NK5Z",
    "signer_lists": true
}
{
    "command": "account_info",
    "account": "rsuUjfWxrACCAwGQDsNeZUhpzXf1n1NK5Z",
    "ledger_index": "61770679",
    "signer_lists": true
}
```
looks like it was broken here, there is no any handling if signers is not exist

https://github.com/XRPLF/clio/commit/c780ef8a0b0a3e735eceea796c89213079c0e812
btw, this works, but it should be rippled response, not clio
```
{
    "command": "account_info",
    "account": "rsuUjfWxrACCAwGQDsNeZUhpzXf1n1NK5Z",
    "ledger_index": "current",
    "signer_lists": true
}
```

## Supporting Files

https://github.com/XRPLF/clio/commit/c780ef8a0b0a3e735eceea796c89213079c0e812

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes #2730

### CODE REVIEW

File: src/rpc/handlers/AccountInfo.cpp [hunk 1]
```diff
@@ -122,8 +123,9 @@ AccountInfoHandler::process(AccountInfoHandler::Input const& input, Context cons
             if (!signersKey.check(sleSigners))
                 return Error{Status{RippledError::rpcDB_DESERIALIZATION}};
 
-            out.signerLists = std::vector<ripple::STLedgerEntry>{sleSigners};
+            signerList.push_back(sleSigners);
         }
+        out.signerLists = std::move(signerList);
```
Comment (kuznetsss) [inline src/rpc/handlers/AccountInfo.cpp]: We could avoid this by creating vector inside `out` at the line 116:
```cpp
out.signerList = std::vector<ripple::STLedgerEntry>();
```
And push into it on the line 126: 
```cpp
out.signerList->push_back(signerList);
```

File: tests/unit/rpc/handlers/AccountInfoTests.cpp [hunk 2]
```diff
@@ -655,6 +655,49 @@ TEST_F(RPCAccountInfoHandlerTest, IdentAndSignerListsFalse)
     });
 }
 
+TEST_F(RPCAccountInfoHandlerTest, EmptySignerLists)
+{
+    auto const ledgerHeader = createLedgerHeader(kLEDGER_HASH, 30);
+    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
+    ON_CALL(*backend_, fetchLedgerBySequence).WillByDefault(Return(ledgerHeader));
```
Comment (kuznetsss) [inline tests/unit/rpc/handlers/AccountInfoTests.cpp]: I know that this is probably copied from another test, but let's use one `EXPECT_CALL().WillOnce()` where possible instead of `EXPECT_CALL()` and `ON_CALL()`

File: tests/unit/rpc/handlers/AccountInfoTests.cpp [hunk 3]
```diff
@@ -208,9 +207,8 @@ TEST_F(RPCAccountInfoHandlerTest, LedgerNonExistViaIntSequence)
 
 TEST_F(RPCAccountInfoHandlerTest, LedgerNonExistViaStringSequence)
 {
-    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
     // return empty ledgerHeader
-    ON_CALL(*backend_, fetchLedgerBySequence(30, _)).WillByDefault(Return(std::nullopt));
```
Comment (mathbunnyru) [inline tests/unit/rpc/handlers/AccountInfoTests.cpp:213]: I think you removed the check of expected input params, let's add it back in these tests?

Comment (PeterChen13579) [reply tests/unit/rpc/handlers/AccountInfoTests.cpp:213]: Ah, you're right. This has an extra check that `fetchLedgerBySequence` must be called with param value of `30`

Comment (mathbunnyru) [reply tests/unit/rpc/handlers/AccountInfoTests.cpp:213]: Yeah, but I think you can have a better syntax and a check for input param as well.

File: tests/unit/rpc/handlers/AccountInfoTests.cpp [hunk 4]
```diff
@@ -655,6 +647,48 @@ TEST_F(RPCAccountInfoHandlerTest, IdentAndSignerListsFalse)
...
+TEST_F(RPCAccountInfoHandlerTest, EmptySignerLists)
+{
+    auto const ledgerHeader = createLedgerHeader(kLEDGER_HASH, 30);
+    EXPECT_CALL(*backend_, fetchLedgerBySequence).WillOnce(Return(ledgerHeader));
+
+    auto const account = getAccountIdWithString(kACCOUNT);
+    auto const accountKk = ripple::keylet::account(account).key;
+    auto const accountRoot = createAccountRootObject(kACCOUNT, 0, 2, 200, 2, kINDEX1, 2);
+    ON_CALL(*backend_, doFetchLedgerObject(accountKk, 30, _))
+        .WillByDefault(Return(accountRoot.getSerializer().peekData()));
```
Comment (kuznetsss) [inline tests/unit/rpc/handlers/AccountInfoTests.cpp:657]: Is it expected to be called more than once? I think it would be better to put a specific number of expected calls here because we should fetch data from db as few times as possible.

Comment (PeterChen13579) [reply tests/unit/rpc/handlers/AccountInfoTests.cpp:657]: It’s only called once, but EXPECT_CALL is not applicable here because this line isn’t verifying behavior, it’s defining mock behavior.
Here we’re just setting up the mock so that fetching the account keylet returns the accountRoot data. The number of times it’s called isn’t what we’re testing in this case.

Comment (kuznetsss) [reply tests/unit/rpc/handlers/AccountInfoTests.cpp:657]: I think it would still better to check that we don't query DB more times than it's actually needed.

**Review by kuznetsss — DISMISSED** [review]
👍

File: tests/unit/rpc/handlers/AccountInfoTests.cpp (hunk 4 above)
Comment (PeterChen13579) [reply tests/unit/rpc/handlers/AccountInfoTests.cpp:657]: Added; Sorry, originally I thought you meant change `on_call` to `expect_call` behavior 😂

**Review by mathbunnyru — APPROVED** [review]
👍
