### PR TITLE
fix: Add CTID to all RPC's that includes transactions

### LINKED ISSUE #1998: Ctid was added to all RPC tx transactions and error code change in rippled responses, should be modified on clio responses to maintain the parity.
## Issue Description

- `tx` with unassociated `network_id` used to return `unknown` error, it was changed to `wrongNetwork`
- CTID was addded on all RPC `tx` transactions.

Please refer the rippled [PR] for additional details(https://github.com/XRPLF/rippled/commit/c4308b216f0cc7b1a33a720b4d38bbc850c4a2f1).

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes #1998

### CODE REVIEW

File: src/rpc/RPCHelpers.cpp [hunk 1]
```diff
@@ -380,6 +380,24 @@ insertMPTIssuanceID(
...
 
+bool
+insertCTID(
+    boost::json::object& jsonObject,
+    uint32_t const ledgerSeq,
+    uint32_t const transactionID,
+    uint32_t const networkID
+)
+{
+    if (transactionID <= 0xFFFFU && ledgerSeq < 0x0FFF'FFFFUL && networkID <= 0xFFFFU) {
```
Comment (PeterChen13579) [inline src/rpc/RPCHelpers.cpp]: fyi logic taken from rippled: https://github.com/XRPLF/rippled/blob/develop/src/xrpld/rpc/handlers/Tx.cpp#L179

File: src/app/ClioApplication.cpp [hunk 2]
```diff
@@ -146,6 +146,10 @@ ClioApplication::run(bool const useNgWebServer)
     // ETL is responsible for writing and publishing to streams. In read-only mode, ETL only publishes
     auto etl = etl::ETLService::makeETLService(config_, ioc, backend, subscriptions, balancer, ledgers);
 
+    // inject networkID into subscriptions, as transaction feed require it to inject CTID in response
+    if (auto const state = etl->getETLState(); state)
+        subscriptions->setNetworkID(state->networkID);
+
```
Comment (kuznetsss) [inline src/app/ClioApplication.cpp]: Maybe this should be done inside `makeETLService()`?

File: src/feed/SubscriptionManager.hpp [hunk 3]
```diff
@@ -332,6 +333,21 @@ class SubscriptionManager : public SubscriptionManagerInterface {
      */
     boost::json::object
     report() const final;
+
+    /**
+     * @brief Set the networkID.
+     * @param networkID The network id to set.
+     */
+    void
+    setNetworkID(uint32_t const networkID) final;
```
Comment (kuznetsss) [inline src/feed/SubscriptionManager.hpp]: `const` doesn't do anything in declaration.

File: src/feed/impl/TransactionFeed.cpp [hunk 4]
```diff
@@ -205,6 +206,11 @@ TransactionFeed::pub(
         rpc::insertDeliverMaxAlias(pubObj[txKey].as_object(), version);
         rpc::insertMPTIssuanceID(pubObj[JS(meta)].as_object(), tx, meta);
 
+        auto const& metaObj = pubObj[JS(meta)];
+        if (metaObj.is_object() && metaObj.as_object().contains("TransactionIndex") &&
+            metaObj.as_object().at("TransactionIndex").is_int64())
```
Comment (kuznetsss) [inline src/feed/impl/TransactionFeed.cpp]: Could this `if` be `false` here? Maybe we should replace it with `ASSERT()`?

File: src/feed/impl/TransactionFeed.hpp [hunk 5]
```diff
@@ -182,12 +182,14 @@ class TransactionFeed {
...
      * @param backend The backend.
+     * @param networkID The network ID.
      */
     void
     pub(data::TransactionAndMetadata const& txMeta,
         ripple::LedgerHeader const& lgrInfo,
         std::shared_ptr<data::BackendInterface const> const& backend,
-        std::shared_ptr<data::AmendmentCenterInterface const> const& amendmentCenter);
+        std::shared_ptr<data::AmendmentCenterInterface const> const& amendmentCenter,
+        uint32_t const networkID = 0);
```
Comment (kuznetsss) [inline src/feed/impl/TransactionFeed.hpp]: Probably better to not put a default value here, because having default value we could miss a place where `networkID` should be passed and it will result in sending incorrect data.

File: src/rpc/RPCHelpers.cpp (hunk 1 above)
Comment (kuznetsss) [reply src/rpc/RPCHelpers.cpp]: Better to add this comment to the code.

File: src/rpc/common/impl/HandlerProvider.cpp [hunk 6]
```diff
@@ -86,7 +86,7 @@ ProductionHandlerProvider::ProductionHandlerProvider(
           {"account_nfts", {.handler = AccountNFTsHandler{backend}}},
           {"account_objects", {.handler = AccountObjectsHandler{backend}}},
           {"account_offers", {.handler = AccountOffersHandler{backend}}},
-          {"account_tx", {.handler = AccountTxHandler{backend}}},
+          {"account_tx", {.handler = AccountTxHandler{backend, etl}}},
```
Comment (kuznetsss) [inline src/rpc/common/impl/HandlerProvider.cpp:89]: Maybe we could pass only `networkID` here? I assume it will not change ever in the same network, right?

File: src/rpc/handlers/Tx.hpp [hunk 7]
```diff
@@ -37,6 +37,7 @@
 #include <boost/json/object.hpp>
 #include <boost/json/value.hpp>
 #include <boost/json/value_to.hpp>
+#include <fmt/core.h>
```
Comment (kuznetsss) [inline src/rpc/handlers/Tx.hpp:40]: This seems to be left from debug.

File: src/feed/impl/TransactionFeed.cpp (hunk 4 above)
Comment (PeterChen13579) [reply src/feed/impl/TransactionFeed.cpp]: I think `TransactionIndex` can be false. The `metaObj.is_object` can be `ASSERT() `yea.

File: src/rpc/common/impl/HandlerProvider.cpp (hunk 6 above)
Comment (PeterChen13579) [reply src/rpc/common/impl/HandlerProvider.cpp:89]: Yea, that's true, unless somehow in the future, rippled allows to swap networks without stopping the server.

File: src/rpc/handlers/Tx.hpp (hunk 7 above)
Comment (PeterChen13579) [reply src/rpc/handlers/Tx.hpp:40]: fmt was already used [in this file](https://github.com/XRPLF/clio/blob/develop/src/rpc/handlers/Tx.hpp#L175) before 😄

File: tests/unit/feed/TransactionFeedTests.cpp [hunk 8]
```diff
@@ -191,10 +191,10 @@ TEST_F(FeedTransactionTest, SubTransactionV1)
 
     EXPECT_CALL(*mockSessionPtr, apiSubversion).WillOnce(testing::Return(1));
     EXPECT_CALL(*mockSessionPtr, send(sharedStringJsonEq(kTRAN_V1)));
-    testFeedPtr->pub(trans1, ledgerHeader, backend_, mockAmendmentCenterPtr_);
+    testFeedPtr->pub(trans1, ledgerHeader, backend_, mockAmendmentCenterPtr_, 0);
```
Comment (kuznetsss) [inline tests/unit/feed/TransactionFeedTests.cpp]: Better to created a named constant in the fixture to make it more readable.

File: src/rpc/RPCHelpers.cpp [hunk 9]
```diff
@@ -380,6 +380,25 @@ insertMPTIssuanceID(
     return false;
 }
 
+bool
+insertCTID(
+    boost::json::object& jsonObject,
+    uint32_t const ledgerSeq,
+    uint32_t const transactionID,
+    uint32_t const networkID
+)
```
Comment (kuznetsss) [inline src/rpc/RPCHelpers.cpp]: Maybe it would be better to change the signature of the function, so the usage will look:
```cpp
jsonObject[JS(ctid)] = makeCTID(ledgerSeq, transactionID, networkID);
```

**Comment by PeterChen13579** [comment]
TODO: We can optimize passing required values into each handler instead of `etl_` https://github.com/XRPLF/clio/issues/2021

File: src/rpc/RPCHelpers.cpp (hunk 9 above)
Comment (PeterChen13579) [reply src/rpc/RPCHelpers.cpp]: Now thinking about it more, I think this function isn't really needed as there was already a `makeCTID` and I can change the logic of that function instead as it matches rippled as well

File: tests/unit/feed/TransactionFeedTests.cpp (hunk 8 above)
Comment (PeterChen13579) [reply tests/unit/feed/TransactionFeedTests.cpp]: Made it constexpr.

**Review by kuznetsss — APPROVED** [review]
👍
