### PR TITLE
fix: Flaky test in ETLng

### LINKED ISSUE #2075: `ExtractionModelNgTests.LedgerDataCopyableAndEquatable` test is flaky
https://github.com/XRPLF/clio/actions/runs/14794633695/job/41538889602

```
[ RUN      ] ExtractionModelNgTests.LedgerDataCopyableAndEquatable
/__w/clio/clio/tests/unit/etlng/ExtractionTests.cpp:96: Failure
Expected: (first) != (third), actual: 312-byte object ...
```

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes a flaky test

Fix: https://github.com/XRPLF/clio/issues/2075

### CODE REVIEW

File: tests/common/util/TestObject.cpp [hunk 1]
```diff
@@ -89,6 +89,8 @@ createLedgerHeader(std::string_view ledgerHash, ripple::LedgerIndex seq, std::op
     ledgerHeader.seq = seq;
 
     if (age) {
+        // Note: be cautios of using small age values as the underlying NetClock precision is seconds
+        // and the small time difference may lead to comparison bugs
```
Comment (kuznetsss) [inline tests/common/util/TestObject.cpp]: Maybe we should add `ASSERT()` here?

File: tests/common/util/TestObject.cpp [hunk 2]
```diff
@@ -89,6 +89,8 @@ createLedgerHeader(std::string_view ledgerHash, ripple::LedgerIndex seq, std::op
     ledgerHeader.seq = seq;
 
     if (age) {
+        // Note: be cautios of using small age values as the underlying NetClock precision is seconds
```
Comment (mathbunnyru) [inline tests/common/util/TestObject.cpp]:
```suggestion
        // Note: be cautious of using age values close to each other as the underlying NetClock precision is seconds
```

😆

Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: Just using a large value won't help - if you provide 10000 and 10001 as values, the comparison will still be flake.
The idea is to provide values which are not close to each other.

Comment (kuznetsss) [reply tests/common/util/TestObject.cpp]: Why precommit hook didn't catch the typo?

File: tests/common/util/TestObject.cpp (hunk 1 above)
Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: Sorry, I don't get it, what will we assert?

File: tests/common/util/TestObject.cpp (hunk 2 above)
Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: https://github.com/crate-ci/typos?tab=readme-ov-file#why-was--not-corrected

> typos maintains a list of known typo corrections to keep the false positive count low so it can safely run unassisted.

> This is in contrast to most spell checking UIs people use where there is a known list of valid words

I think it might not be in the corrections list.

Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: I checked `typos --files` and this test file shows up (as expected).
And looked at the `words.csv` here: https://raw.githubusercontent.com/crate-ci/typos/refs/heads/master/crates/typos-dict/assets/words.csv
Haven't found `cautios` there.

Comment (kuznetsss) [reply tests/common/util/TestObject.cpp]: Submited to typos's list of additions: https://github.com/crate-ci/typos/issues/1264#issuecomment-2847271667

File: tests/common/util/TestObject.cpp (hunk 1 above)
Comment (kuznetsss) [reply tests/common/util/TestObject.cpp]: Assert that the value is big enough, but if it should be different from other values, we could't add an assertion here.

Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: Yep, that's exactly why I was asking. So, the best we could do is to write a good comment.

File: tests/common/util/TestObject.cpp (hunk 2 above)
Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: Nice one, thanks!

**Review by mathbunnyru — APPROVED** [review]
👍
