### PR TITLE
Fix quoteAsset value in getAggregatePrice

### LINKED ISSUE #1373: [get_aggregate_price] with malformed quote_asset value returns different error on Clio compared to rippled
## Issue Description

Clio returns `invalidParams` whereas rippled returns `objectNotFound` with malformed quote_asset values in get_aggregate_price

## Steps to Reproduce

- Create two oracles.
- Send a get_aggregate_price request with malformed trim value.
- Malformed quote_asset values: `None`, `123`, `-1`, `0`, `1.2`

Request:
```json 

{
  "method": "get_aggregate_price",
  "params": [
    {
      "base_asset": "BTC",
      "quote_asset": 123,
      "oracles": [
        {
          "account": "rwz8i5bUKa12tYxQjsSuzDQaBwKkuGUqa5",
          "oracle_document_id": 1
        },
        {
          "account": "rDtBhKmzKveCSd5jmrcQD6CU8kidCLCy7h",
          "oracle_document_id": 1
        }
      ]
    }
  ]
}
```  

## Expected Result

Rippled response:
```json 
{
    "result": {
        "error": "objectNotFound",
        "error_code": 92,
        "error_message": "The requested object was not found.",
        "ledger_current_index": 82571,
        "request": {
            "base_asset": "BTC",
            "command": "get_aggregate_price",
            "oracles": [
                {
                    "account": "rwz8i5bUKa12tYxQjsSuzDQaBwKkuGUqa5",
                    "oracle_document_id": 1
                },
                {
                    "account": "rDtBhKmzKveCSd5jmrcQD6CU8kidCLCy7h",
                    "oracle_document_id": 1
                }
            ],
            "quote_asset": 123
        },
        "status": "error",
        "validated": false
    }
}
```  

## Actual Result

Clio response:
```json 
{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "Invalid parameters.",
        "status": "error",
        "type": "response",
        "request": {
            "method": "get_aggregate_price",
            "params": [
                {
                    "base_asset": "BTC",
                    "quote_asset": 123,
                    "oracles": [
                        {
                            "account": "rwz8i5bUKa12tYxQjsSuzDQaBwKkuGUqa5",
                            "oracle_document_id": 1
                        },
                        {
                            "account": "rDtBhKmzKveCSd5jmrcQD6CU8kidCLCy7h",
                            "oracle_document_id": 1
                        }
                    ]
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by PeterChen13579**
Fixes #1373

### CODE REVIEW

File: src/rpc/handlers/GetAggregatePrice.hpp [hunk 1]
```diff
@@ -155,14 +164,26 @@ class GetAggregatePriceHandler {
...
+
         static auto const rpcSpec = RpcSpec{
             {JS(ledger_hash), validation::Uint256HexStringValidator},
             {JS(ledger_index), validation::LedgerIndexValidator},
             // note: Rippled's base_asset and quote_asset can be non-string. It will eventually return
             // "rpcOBJECT_NOT_FOUND". Clio will return "rpcINVALID_PARAMS" if the base_asset or quote_asset is not a
             // string. User can clearly know there is a mistake in the input.
             {JS(base_asset), validation::Required{}, validation::Type<std::string>{}},
-            {JS(quote_asset), validation::Required{}, validation::Type<std::string>{}},
+            {JS(quote_asset), validation::Required{}, validateQuoteAsset},
```
Comment (cindyyan317) [inline src/rpc/handlers/GetAggregatePrice.hpp]: Maybe we can make it simpler by calling :
meta::WithCustomError{validation::CurrencyValidator, Status(RippledError::InvalidParam)}

File: src/rpc/handlers/GetAggregatePrice.hpp [hunk 2]
```diff
@@ -22,18 +22,22 @@
...
 #include "rpc/JS.hpp"
+#include "rpc/common/MetaProcessors.hpp"
 #include "rpc/common/Specs.hpp"
 #include "rpc/common/Types.hpp"
 #include "rpc/common/Validators.hpp"
 
 #include <boost/asio/spawn.hpp>
 #include <boost/json/array.hpp>
 #include <boost/json/conversion.hpp>
+#include <boost/json/value_to.hpp>
```
Comment (cindyyan317) [inline src/rpc/handlers/GetAggregatePrice.hpp]: we don't need such headers ,right?

**Review by kuznetsss — DISMISSED** [review]
👍

**Review by cindyyan317 — DISMISSED** [review]

**Review by kuznetsss — APPROVED** [review]
