### PR TITLE
fix: mpt_issuance_id not in tx for MPTIssuanceCreate

### LINKED ISSUE #2332: Add MPT related txns into issuer's AccountTx RPC
## Issue Description

Rippled PR: https://github.com/XRPLF/rippled/commit/b8626ea3c66b05ed754f62ae89e46f3a0d91dcb3

## Steps to Reproduce

Sample request:
```
{
    "method": "account_tx",
    "params": [
        {
            "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ"
        }
    ]
}
```

## Expected Result

Rippled response:
```
{
    "result": {
        "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
        "ledger_index_max": 4465482,
        "ledger_index_min": 4464490,
        "limit": 0,
        "status": "success",
        "transactions": [
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Flags": 0,
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "OutstandingAmount": "10000",
                                    "OwnerNode": "0",
                                    "Sequence": 4465445
                                },
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "PreviousFields": {
                                    "OutstandingAmount": "0"
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999800",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465447
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "39999900",
                                    "Sequence": 4465446
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Flags": 0,
                                    "MPTAmount": "10000",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                                    "OwnerNode": "0"
                                },
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "PreviousFields": {},
                                "PreviousTxnID": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                                "PreviousTxnLgrSeq": 4465451
                            }
                        }
                    ],
                    "TransactionIndex": 5,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    }
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "DeliverMax": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "Destination": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "Sequence": 4465446,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "Payment",
                    "TxnSignature": "3044022041AAB1103CC12594B8CEBFCDCE00DE79BCCB4CBAE5783FA5A15F8A22ACA6110F022008E6235A58090EFAEDE873C7F67E9635622915ADD66DF645ECE0544CFE0D998A",
                    "ctid": "C044232D00050002",
                    "date": 805830251,
                    "hash": "C51EFC6ED34E7B33B13FAA425383AEBEC4F2BDBB6DAEFDDBBABC051D862B66BA",
                    "inLedger": 4465453,
                    "ledger_index": 4465453
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465450
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "95B3155BF1D65091FC248D913FD8E4AB03013DD6DC3EC3F834C6DB9F40D8F248",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465449
                                },
                                "PreviousTxnID": "2B63151BCB3D8DCD4837331A072E91F1DDFBB24A0CFC9317624DE87A16B0C2CE",
                                "PreviousTxnLgrSeq": 4465449
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "NewFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                                }
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "D333D883E263D617335A97F102869EFEBAB9945294FACF746E8D85EB079B2611",
                                "NewFields": {
                                    "Owner": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "RootIndex": "D333D883E263D617335A97F102869EFEBAB9945294FACF746E8D85EB079B2611"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 15,
                    "TransactionResult": "tesSUCCESS"
                },
                "tx": {
                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                    "Sequence": 4465449,
                    "SigningPubKey": "02FD485E8014F7B63964645E6B7D1459EE992299D62931D8A08DDA37EE6A4CA597",
                    "TransactionType": "MPTokenAuthorize",
                    "TxnSignature": "3044022041828EDC333C633284577586D8E373AF21D4C525FB17A1F4917E623F74A996A4022009FC6E830E6FB3F8D9052F7AC97F648FB2E20DFEBA8D1A3487BC507B702A4B05",
                    "ctid": "C044232B000F0002",
                    "date": 805830243,
                    "hash": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                    "inLedger": 4465451,
                    "ledger_index": 4465451
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "NewFields": {
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465446
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465445
                                },
                                "PreviousTxnID": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                                "PreviousTxnLgrSeq": 4465445
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B",
                                "NewFields": {
                                    "Owner": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "RootIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 12,
                    "TransactionResult": "tesSUCCESS",
                    "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465445,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "MPTokenIssuanceCreate",
                    "TxnSignature": "3045022100B7330D8C22ECC4ABF12306829FAE9145382949240D41E5822C0263482C1B9CFE02200AA4FB6A4E0549E0419B53D1F0AEFC5D70E0B7CB05B76DF8BCD8DDE761DAF23A",
                    "ctid": "C0442327000C0002",
                    "date": 805830231,
                    "hash": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                    "inLedger": 4465447,
                    "ledger_index": 4465447
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "NewFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "40000000",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                                    "Balance": "99799999500",
                                    "Flags": 0,
                                    "OwnerCount": 0,
                                    "Sequence": 4465436
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "E30641084BA9892565B5FD310BFB123CDD3C084301F7A44A119FAEF28684900B",
                                "PreviousFields": {
                                    "Balance": "99839999600",
                                    "Sequence": 4465435
                                },
                                "PreviousTxnID": "EB16466C1A88E4DE46F45C827CF0BC459CE322A54318AF9184177F5D58EE503D",
                                "PreviousTxnLgrSeq": 4465441
                            }
                        }
                    ],
                    "TransactionIndex": 1,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": "40000000"
                },
                "tx": {
                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                    "Amount": "40000000",
                    "DeliverMax": "40000000",
                    "Destination": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465435,
                    "SigningPubKey": "0248B7B2CFFCF2FEF8A58F4E9CE5CBE52C9C66C2E89B6B79262FCD5AC182C63550",
                    "TransactionType": "Payment",
                    "TxnSignature": "304402206E6C43ED15F19791AA185565FBC3EAE9AD03B98D5D59A66FD2D2C8202E11A0DF022032AE14C8BC67F7DAEF6A1252519E34CB6B369519E09A079D32456BE7033A1B54",
                    "ctid": "C044232500010002",
                    "date": 805830222,
                    "hash": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                    "inLedger": 4465445,
                    "ledger_index": 4465445
                },
                "validated": true
            }
        ],
        "validated": true
    }
}
```

## Actual Result

Clio response:

```
{
    "result": {
        "account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
        "ledger_index_min": 4465121,
        "ledger_index_max": 4465490,
        "transactions": [
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Flags": 0,
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "OutstandingAmount": "10000",
                                    "OwnerNode": "0",
                                    "Sequence": 4465445
                                },
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "PreviousFields": {
                                    "OutstandingAmount": "0"
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999800",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465447
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "39999900",
                                    "Sequence": 4465446
                                },
                                "PreviousTxnID": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                                "PreviousTxnLgrSeq": 4465447
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                                    "Flags": 0,
                                    "MPTAmount": "10000",
                                    "MPTokenIssuanceID": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                                    "OwnerNode": "0"
                                },
                                "LedgerEntryType": "MPToken",
                                "LedgerIndex": "9DD6FD37827887BE3640E3C4756FE591E9EF6BE38C62DA56631EC70B3BC45157",
                                "PreviousFields": {},
                                "PreviousTxnID": "084C8994EC82DC9ADDD630F8B48AD2C7BFAA46719A30A2380A5BFC3B14E841D6",
                                "PreviousTxnLgrSeq": 4465451
                            }
                        }
                    ],
                    "TransactionIndex": 5,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    }
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Amount": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "Destination": "rLunQu9tFALsnQkuGfQm3u8fcfnsoTDV4v",
                    "Fee": "100",
                    "Sequence": 4465446,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "Payment",
                    "TxnSignature": "3044022041AAB1103CC12594B8CEBFCDCE00DE79BCCB4CBAE5783FA5A15F8A22ACA6110F022008E6235A58090EFAEDE873C7F67E9635622915ADD66DF645ECE0544CFE0D998A",
                    "hash": "C51EFC6ED34E7B33B13FAA425383AEBEC4F2BDBB6DAEFDDBBABC051D862B66BA",
                    "DeliverMax": {
                        "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A",
                        "value": "10000"
                    },
                    "ctid": "C044232D00050002",
                    "date": 805830251,
                    "ledger_index": 4465453,
                    "inLedger": 4465453
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "MPTokenIssuance",
                                "LedgerIndex": "6D60B36BD1E362DD0E4BF7D6A5DC756E63D8262C1DC24E3B25D5E9ECA250267B",
                                "NewFields": {
                                    "Issuer": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "39999900",
                                    "Flags": 0,
                                    "OwnerCount": 1,
                                    "Sequence": 4465446
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "PreviousFields": {
                                    "Balance": "40000000",
                                    "OwnerCount": 0,
                                    "Sequence": 4465445
                                },
                                "PreviousTxnID": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                                "PreviousTxnLgrSeq": 4465445
                            }
                        },
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "DirectoryNode",
                                "LedgerIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B",
                                "NewFields": {
                                    "Owner": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "RootIndex": "9810A35ED1E319A941325F1419151262E0C09EA916250062E938A6984B2CE07B"
                                }
                            }
                        }
                    ],
                    "TransactionIndex": 12,
                    "TransactionResult": "tesSUCCESS",
                    "mpt_issuance_id": "00442325C3B758DBD6C373A239CEBC897B6531B47ED03B4A"
                },
                "tx": {
                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465445,
                    "SigningPubKey": "02E9C822BC32CCA8B0945B7893220F60EA78B29ABEC22A81FA29D2CD22F88940FA",
                    "TransactionType": "MPTokenIssuanceCreate",
                    "TxnSignature": "3045022100B7330D8C22ECC4ABF12306829FAE9145382949240D41E5822C0263482C1B9CFE02200AA4FB6A4E0549E0419B53D1F0AEFC5D70E0B7CB05B76DF8BCD8DDE761DAF23A",
                    "hash": "4E34C7A3E351421FCBB41C96A97D63B39289526DFBED629B800997FD9506909F",
                    "ctid": "C0442327000C0002",
                    "date": 805830231,
                    "ledger_index": 4465447,
                    "inLedger": 4465447
                },
                "validated": true
            },
            {
                "meta": {
                    "AffectedNodes": [
                        {
                            "CreatedNode": {
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "7E3FCF03924AEB70FAC46CA96A7FCFE47A5F2084C713480F621A7810E1FC3960",
                                "NewFields": {
                                    "Account": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                                    "Balance": "40000000",
                                    "Sequence": 4465445
                                }
                            }
                        },
                        {
                            "ModifiedNode": {
                                "FinalFields": {
                                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                                    "Balance": "99799999500",
                                    "Flags": 0,
                                    "OwnerCount": 0,
                                    "Sequence": 4465436
                                },
                                "LedgerEntryType": "AccountRoot",
                                "LedgerIndex": "E30641084BA9892565B5FD310BFB123CDD3C084301F7A44A119FAEF28684900B",
                                "PreviousFields": {
                                    "Balance": "99839999600",
                                    "Sequence": 4465435
                                },
                                "PreviousTxnID": "EB16466C1A88E4DE46F45C827CF0BC459CE322A54318AF9184177F5D58EE503D",
                                "PreviousTxnLgrSeq": 4465441
                            }
                        }
                    ],
                    "TransactionIndex": 1,
                    "TransactionResult": "tesSUCCESS",
                    "delivered_amount": "40000000"
                },
                "tx": {
                    "Account": "rDR3nozNRGbwP6h7H9WiEjShahXn8rYg3q",
                    "Amount": "40000000",
                    "Destination": "rJqiQbsxhZ5SmE13nxXCUip4cYPk9JpVfQ",
                    "Fee": "100",
                    "Sequence": 4465435,
                    "SigningPubKey": "0248B7B2CFFCF2FEF8A58F4E9CE5CBE52C9C66C2E89B6B79262FCD5AC182C63550",
                    "TransactionType": "Payment",
                    "TxnSignature": "304402206E6C43ED15F19791AA185565FBC3EAE9AD03B98D5D59A66FD2D2C8202E11A0DF022032AE14C8BC67F7DAEF6A1252519E34CB6B369519E09A079D32456BE7033A1B54",
                    "hash": "15FF2572D63CC5E546E6C7F547F275FE7D4894BE85E3DFA9113646020435AC07",
                    "DeliverMax": "40000000",
                    "ctid": "C044232500010002",
                    "date": 805830222,
                    "ledger_index": 4465445,
                    "inLedger": 4465445
                },
                "validated": true
            }
        ],
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes: #2332

### CODE REVIEW

**Review by kuznetsss — COMMENTED** [review]
Looks, good, but could you please add unit tests where possible?

File: src/rpc/RPCHelpers.cpp [hunk 1]
```diff
@@ -317,6 +318,68 @@ insertDeliveredAmount(
...
+    if (txnJson.contains(JS(TransactionType)) && txnJson.at(JS(TransactionType)).is_string() and
+        txnJson.at(JS(TransactionType)).as_string() == JS(MPTokenIssuanceCreate))
+        return false;
+
+    if (auto const id = getMPTIssuanceID(meta)) {
+        txnJson[JS(mpt_issuance_id)] = ripple::to_string(*id);
+        return true;
+    }
+
+    assert(false);
```
Comment (mathbunnyru) [inline src/rpc/RPCHelpers.cpp]: Please, use our `ASSERT`

File: src/rpc/RPCHelpers.cpp [hunk 2]
```diff
@@ -317,6 +318,68 @@ insertDeliveredAmount(
...
+    return false;
```
Comment (mathbunnyru) [inline src/rpc/RPCHelpers.cpp]: This can be simplified, you can write it like:
```
auto const id = ...;
ASSERT(id.has_value());
assign
return true
```

File: src/rpc/RPCHelpers.cpp [hunk 3]
```diff
@@ -317,6 +318,68 @@ insertDeliveredAmount(
...
+canHaveMPTIssuanceID(boost::json::object const& txnJson, std::shared_ptr<ripple::TxMeta const> const& meta)
+{
+    if (txnJson.at(JS(TransactionType)).is_string() and
+        not boost::iequals(txnJson.at(JS(TransactionType)).as_string(), JS(MPTokenIssuanceCreate)))
+        return false;
+
+    if (meta->getResultTER() != ripple::tesSUCCESS)
+        return false;
+
+    return true;
```
Comment (mathbunnyru) [inline src/rpc/RPCHelpers.cpp:359]:
```suggestion
    return meta->getResultTER() == ripple::tesSUCCESS;
```

File: src/rpc/RPCHelpers.hpp [hunk 4]
```diff
@@ -199,6 +199,18 @@ insertDeliveredAmount(
...
 );
 
+/**
+ * @brief Add "mpt_issuance_id" into various MPTToken transaction json.
+ * @note We exclude "mpt_issuance_id" for MPTokenIssuanceCreate only. The reason is because the mpt_issuance_id
+ * is generated only after one submits MPTokenIssuanceCreate, so there’s no way to know what the id is. (rippled)
+ *
+ * @param txnJson The transaction Json object
+ * @param meta The metadata object
+ * @return true if the "mpt_issuance_id" is added to the tx json object
```
Comment (mathbunnyru) [inline src/rpc/RPCHelpers.hpp]:
```suggestion
 * @return true if the "mpt_issuance_id" is added to the txnJson JSON object
```

**Review by mathbunnyru — CHANGES_REQUESTED** [review]

**Review by mathbunnyru — APPROVED** [review]
