### PR TITLE
fix: Add domain to book_changes

### LINKED ISSUE #2221: Domain is missing from Clio book_changes response(Version: [20250612161611-develop-0273ba0d])
## Steps to Reproduce

-  Subscribe to book_changes and include domain.
- Trigger book change by crossing an offer within the same domain.

## Expected Result

Rippled book_change response:

```
{
  'changes': [
    {
      'close': '1',
      'currency_a': 'XRP_drops',
      'currency_b': 'rKWPJTHgd5YKbmrHoLeLvueucvxcrrGgv8/USD',
      'domain': '732CE1B42680CA8472DB5F88DC5E1128103BEFFAC8CF3A9EBFB22EC534C608D4',
      'high': '1',
      'low': '1',
      'open': '1',
      'volume_a': '10000',
      'volume_b': '10000'
    }
  ],
  'ledger_hash': 'FE77A810B8F1CDC61135D8987CFE06A2406FF061C6559ADE661564BAC78C691A',
  'ledger_index': 2683,
  'ledger_time': 803070644,
  'type': 'bookChanges',
  'validated': True
}
```

## Actual Result

Clio book_change response:

```
{
  'type': 'bookChanges',
  'ledger_index': 2683,
  'ledger_hash': 'FE77A810B8F1CDC61135D8987CFE06A2406FF061C6559ADE661564BAC78C691A',
  'ledger_time': 803070644,
  'changes': [
    {
      'currency_a': 'XRP_drops',
      'currency_b': 'rKWPJTHgd5YKbmrHoLeLvueucvxcrrGgv8/USD',
      'volume_a': '10000',
      'volume_b': '10000',
      'high': '1',
      'low': '1',
      'open': '1',
      'close': '1'
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix: https://github.com/XRPLF/clio/issues/2221

### CODE REVIEW

File: src/rpc/BookChangesHelper.hpp [hunk 1]
```diff
@@ -265,6 +265,8 @@ tag_invoke(boost::json::value_from_tag, boost::json::value& jv, BookChange const
         {JS(open), to_string(change.openRate.iou())},
         {JS(close), to_string(change.closeRate.iou())},
     };
+    if (change.domain)
```
Comment (godexsoft) [inline src/rpc/BookChangesHelper.hpp]: nit: Let's add a line of space before the `if` 👍

Comment (godexsoft) [reply src/rpc/BookChangesHelper.hpp]: nit: Consider using `has_value()` for readability

File: tests/common/util/TestObject.cpp [hunk 2]
```diff
@@ -330,13 +330,16 @@ createMetaDataForBookChange(
     int finalTakerGets,
     int perviousTakerGets,
     int finalTakerPays,
-    int perviousTakerPays
+    int perviousTakerPays,
+    std::optional<std::string_view> const& domain
```
Comment (godexsoft) [inline tests/common/util/TestObject.cpp]: nit: Maybe we should just pass by copy since it's a string_view inside of optional?

File: tests/unit/rpc/handlers/BookChangesTests.cpp [hunk 3]
```diff
@@ -222,3 +223,51 @@ TEST_F(RPCBookChangesHandlerTest, NormalPath)
         EXPECT_EQ(*output.result, json::parse(kEXPECTED_OUT));
     });
 }
+
+TEST_F(RPCBookChangesHandlerTest, NormalPathWithDomain)
+{
+    static constexpr auto kEXPECTED_OUT =
+        R"JSON({
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/BookChangesTests.cpp:227]: nit: Formatting of JSON could be improved a bit :)

File: tests/unit/rpc/handlers/BookChangesTests.cpp [hunk 4]
```diff
@@ -222,3 +223,51 @@ TEST_F(RPCBookChangesHandlerTest, NormalPath)
...
+                    "high":"-1",
+                    "low":"-1",
+                    "open":"-1",
+                    "close":"-1",
+                    "domain":"F10D0CC9A0F9A3CBF585B80BE09A186483668FDBDD39AA7E3370F3649CE134E5"
+                }
+            ]
+        })JSON";
+
+    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/BookChangesTests.cpp]: nit: Times(1) is default (here and below)

**Review by godexsoft — CHANGES_REQUESTED** [review]

File: tests/unit/rpc/handlers/BookChangesTests.cpp (hunk 3 above)
Comment (mathbunnyru) [reply tests/unit/rpc/handlers/BookChangesTests.cpp:227]: Improved in the whole file

File: tests/unit/rpc/handlers/BookChangesTests.cpp (hunk 4 above)
Comment (mathbunnyru) [reply tests/unit/rpc/handlers/BookChangesTests.cpp]: Improved in the whole file

File: tests/common/util/TestObject.cpp (hunk 2 above)
Comment (mathbunnyru) [reply tests/common/util/TestObject.cpp]: i think it makes sense, since object size is small
thanks, changed 👍

File: tests/unit/rpc/handlers/BookChangesTests.cpp [hunk 5]
```diff
@@ -138,11 +139,11 @@ TEST_F(RPCBookChangesHandlerTest, LedgerNonExistViaIntSequence)
 
 TEST_F(RPCBookChangesHandlerTest, LedgerNonExistViaStringSequence)
 {
-    EXPECT_CALL(*backend_, fetchLedgerBySequence).Times(1);
+    EXPECT_CALL(*backend_, fetchLedgerBySequence);
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/BookChangesTests.cpp:142]: EXPECT_CALL and ON_CALL can and should be merged into one

File: tests/common/util/TestObject.hpp [hunk 6]
```diff
@@ -184,7 +184,8 @@ createMetaDataForBookChange(
     int finalTakerGets,
     int perviousTakerGets,
     int finalTakerPays,
-    int perviousTakerPays
+    int perviousTakerPays,
+    std::optional<std::string_view> const domain = std::nullopt
```
Comment (godexsoft) [inline tests/common/util/TestObject.hpp]: const by-value params are stupid

File: tests/unit/rpc/handlers/BookChangesTests.cpp [hunk 7]
```diff
@@ -138,11 +139,11 @@ TEST_F(RPCBookChangesHandlerTest, LedgerNonExistViaIntSequence)
...
     // return empty ledgerHeader
     ON_CALL(*backend_, fetchLedgerBySequence(kMAX_SEQ, _)).WillByDefault(Return(std::nullopt));
 
-    auto static const kINPUT = json::parse(R"JSON({"ledger_index":"30"})JSON");
+    auto static const kINPUT = json::parse(R"JSON({"ledger_index": "30"})JSON");
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/BookChangesTests.cpp]: nit: Let's change to `static auto const`. we can update other places separately

**Review by godexsoft — CHANGES_REQUESTED** [review]

File: tests/unit/rpc/handlers/BookChangesTests.cpp (hunk 5 above)
Comment (mathbunnyru) [reply tests/unit/rpc/handlers/BookChangesTests.cpp:142]: Thanks, done

**Review by godexsoft — APPROVED** [review]
Nice 👍
