### PR TITLE
fix: AsyncFramework RAII

### LINKED ISSUE #1812: AsyncFramework operation needs proper RAII
## Issue Description
At the moment, if any of the operations that the user is holding onto is deleted, the underlying async operation is not automatically cancelled/aborted. This does not feel right.

## Expected Result
Any operation in async framework should automatically abort itself if the user no longer holds onto its handle.

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes #1812 

AsyncFramework operations were not handling their destruction properly. With this fix operations will automatically cancel/abort if they go out of scope (i.e. the user is no longer holding onto them).

### CODE REVIEW

File: src/util/WasMoved.hpp [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+     * @brief The function to be used by clients in order to check whether the instance was moved from
+     * @return true if moved from; false otherwise
+     */
+    [[nodiscard]] bool
+    wasMoved() const noexcept
+    {
+        return wasMoved_;
+    }
+
+protected:
```
Comment (kuznetsss) [inline src/util/WasMoved.hpp]:
```suggestion

```
`protected` 2 times.

File: src/util/WasMoved.hpp [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    WasMoved() = default;  // should only be used via inheritance
+
+public:
+    ~WasMoved() = default;
```
Comment (kuznetsss) [inline src/util/WasMoved.hpp]:
```suggestion
    virtual ~WasMoved() = default;
```

File: src/util/WasMoved.hpp [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+
+    /**
+     * @brief Move constructor sets the internal flag to true on the moved-from object
+     * @param other the moved-from object
+     */
+    WasMoved(WasMoved&& other)
+    {
+        other.wasMoved_ = true;
```
Comment (kuznetsss) [inline src/util/WasMoved.hpp]: Hm, shouldn't we set here `wasMoved_ = false;`?
To fix such case:
```cpp
WasMoved a;
WasMoved b = std::move(a);
a = std::move(b);
EXPECT_FALSE(a.wasMoved());
```

Comment (kuznetsss) [reply src/util/WasMoved.hpp]: Also probably better to reuse code:
```cpp
*this = std::move(other);
```

File: src/util/async/Operation.hpp [hunk 4]
```diff
@@ -149,7 +161,8 @@ struct BasicScheduledOperation {
  * @tparam StopSourceType The type of the stop source
  */
 template <typename RetType, typename StopSourceType>
-class StoppableOperation : public impl::BasicOperation<StoppableOutcome<RetType, StopSourceType>> {
+class StoppableOperation : public impl::BasicOperation<StoppableOutcome<RetType, StopSourceType>>,
+                           public util::WasMoved {
```
Comment (kuznetsss) [inline src/util/async/Operation.hpp]: Shouldn't the `BasicOperation` class inherit `WasMoved` instead?

File: src/util/WasMoved.hpp (hunk 1 above)
Comment (godexsoft) [reply src/util/WasMoved.hpp]: This one was on purpose actually. It's a common pattern, usually used to separate data from logic but in this case perhaps it's not really helping much so i'll apply your suggestion.

File: src/util/WasMoved.hpp (hunk 2 above)
Comment (godexsoft) [reply src/util/WasMoved.hpp]: Oh yeah, i actually remembered about this in bed last night 😃

File: src/util/async/Operation.hpp (hunk 4 above)
Comment (godexsoft) [reply src/util/async/Operation.hpp]: I deliberately inherited on the same level where we actually need the `wasMoved()` call.

File: src/util/WasMoved.hpp [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+    /**
+     * @brief Move operator sets the internal flag to true on the moved-from object
+     * @param other the moved-from object
+     * @return reference to self
+     */
+    WasMoved&
+    operator=(WasMoved&& other)
+    {
+        other.wasMoved_ = true;
```
Comment (cindyyan317) [inline src/util/WasMoved.hpp]: We may need to check if other is the current object to handle self assignment .
```
WasMoved a; 
a = std::move(a); 
EXPECT_FALSE(a.wasMoved());
```

File: src/util/WasMoved.hpp (hunk 3 above)
Comment (godexsoft) [reply src/util/WasMoved.hpp]: Good suggestions 👍

File: tests/unit/util/MoveTrackerTests.cpp [hunk 6]
```diff
@@ -38,3 +38,13 @@ TEST(WasMovedTests, SimpleChecks)
...
+
+TEST(MoveTrackerTests, SupportReuse)
+{
+    auto original = MoveMe();
+    auto other = std::move(original);
+
+    original = std::move(other);
+    EXPECT_FALSE(original.wasMoved());
+    EXPECT_TRUE(other.wasMoved());
+}
```
Comment (kuznetsss) [inline tests/unit/util/MoveTrackerTests.cpp:50]: Lets also add a test about moving into itself: `moveMe = std::move(moveMe);`

File: src/util/WasMoved.hpp (hunk 5 above)
Comment (godexsoft) [reply src/util/WasMoved.hpp]: That's caught by the compiler already.. explicit self-move is not allowed. 
We can however trick the compiler to do it anyway and the current behaviour ends up with `wasMoved()` equal to `false` which feels correct because you don't actually move anything (if all client move code is doing the correct things). We could also ASSERT instead in such case. WDYT?

Comment (godexsoft) [reply src/util/WasMoved.hpp]: Ok I think we figured out the correct logic. Take a look at the current tests 👍

**Review by kuznetsss — APPROVED** [review]
👍

**Review by cindyyan317 — APPROVED** [review]
👍
