### PR TITLE
fix: Fix incorrect requests logging

### LINKED ISSUE #2004: Log request instead of params
## Issue Description

Clio logs only part of requests. `requests` and `tag` should be passed here:
https://github.com/XRPLF/clio/blob/develop/src/web/RPCServerHandler.hpp#L200

### PR DESCRIPTION
**Pull request by kuznetsss**
Fixes #2004.

### CODE REVIEW

File: src/rpc/RPCHelpers.hpp [hunk 1]
```diff
@@ -744,12 +745,13 @@ decodeCTID(T const ctid) noexcept
  * @brief Log the duration of the request processing
  *
  * @tparam T The type of the duration
- * @param ctx The context of the request
+ * @param request The request to log
+ * @param tag The tag of the context of the request
  * @param dur The duration to log
  */
 template <typename T>
```
Comment (godexsoft) [inline src/rpc/RPCHelpers.hpp]: While you are here, can we change `T` to `Duration` or `DurationType`? `T` is such a generic name.. 🙇

File: tests/unit/rpc/RPCHelpersTests.cpp [hunk 2]
```diff
@@ -1166,3 +1174,71 @@ TEST_P(IsAdminCmdParameterTest, Test)
...
+        {
+        }
+    };
+    DummyTaggable taggable{tagFactory};
+};
+
+TEST_P(RPCHelpersLogDurationTest, LogDuration)
+{
+    auto const& tag = taggable.tag();
+    // TOOD: Update after https://github.com/XRPLF/clio/issues/1668
```
Comment (godexsoft) [inline tests/unit/rpc/RPCHelpersTests.cpp]: This is so going to be lost in time 😆 
What i suggest is let's create a new issue specifically for this change and make it dependant on 1668. Then we eventually will get to it in our list of issues and we will know that it depends on 1668 👍

**Review by godexsoft — CHANGES_REQUESTED** [review]
Cool 🚀 Left a few suggestions 👍

File: tests/unit/rpc/RPCHelpersTests.cpp (hunk 2 above)
Comment (kuznetsss) [reply tests/unit/rpc/RPCHelpersTests.cpp]: Created a child issue, updated TODO and left a comment in the issue to not forget.
https://github.com/XRPLF/clio/issues/2008

**Review by godexsoft — APPROVED** [review]
🚀
