### PR TITLE
fix: Keep spdlog loggers valid between tests

### LINKED ISSUE #2451: Better Data initialization in LogService
1. Data has no constructor nor default values, so the values are undefined by default
2. Users might call LogService::registerLogger before init

### PR DESCRIPTION
**Pull request by mathbunnyru**
Fix: https://github.com/XRPLF/clio/issues/2451

### CODE REVIEW

File: src/util/log/Logger.cpp [hunk 1]
```diff
@@ -238,46 +241,77 @@ getMinSeverity(config::ClioConfigDefinition const& config, Severity defaultSever
...
+    sinks_ = sinks;
+    initialized_ = true;
+
+    spdlog::apply_all([](std::shared_ptr<spdlog::logger> logger) {
+        logger->set_level(toSpdlogLevel(defaultSeverity_));
+    });
+
+    if (isAsync) {
+        // Create a thread pool with 8192 queue size and 1 thread
+        spdlog::init_thread_pool(8192, 1);
```
Comment (godexsoft) [inline src/util/log/Logger.cpp]: nit: Instead of comments you could have two constants here

File: src/util/log/Logger.cpp [hunk 2]
```diff
@@ -56,7 +56,10 @@
 
 namespace util {
 
-LogService::Data LogService::data{};
+bool LogServiceState::isAsync_{true};
```
Comment (godexsoft) [inline src/util/log/Logger.cpp:59]: nit: I don't really mind but the naming is inconsistent with `initialized_`

File: src/util/log/Logger.cpp [hunk 3]
```diff
@@ -238,46 +241,77 @@ getMinSeverity(config::ClioConfigDefinition const& config, Severity defaultSever
...
+    if (isAsync) {
+        // Create a thread pool with 8192 queue size and 1 thread
+        spdlog::init_thread_pool(8192, 1);
+    }
+}
+
+void
+LogServiceState::reset()
+{
+    if (!initialized_) {
```
Comment (godexsoft) [inline src/util/log/Logger.cpp]: nit: You now have a function for this

File: src/util/log/Logger.cpp [hunk 4]
```diff
@@ -307,20 +357,23 @@ LogService::init(config::ClioConfigDefinition const& config)
...
     return {};
 }
 
 void
 LogService::shutdown()
 {
-    spdlog::shutdown();
+    if (initialized_ && isAsync_) {
+        // We run in async mode in production, so we need to make sure all logs are flushed before shutting down
+        spdlog::shutdown();
```
Comment (godexsoft) [inline src/util/log/Logger.cpp:382]: nit: Does it hurt to do that regardless?

File: src/util/log/Logger.hpp [hunk 5]
```diff
@@ -229,26 +232,68 @@ class Logger final {
...
+     * @brief Register a new logger for the specified channel.
+     *
+     * Creates and registers a new spdlog logger instance for the given channel
+     * with the specified or default severity level.
+     *
+     * @param channel The name of the logging channel
+     * @param severity Optional severity level override; uses default if not specified
+     * @return Shared pointer to the registered spdlog logger
+     */
     static std::shared_ptr<spdlog::logger>
```
Comment (godexsoft) [inline src/util/log/Logger.hpp:293]: Do we want this to be nodiscard or not?

File: tests/common/util/LoggerFixtures.hpp [hunk 6]
```diff
@@ -19,37 +19,38 @@
...
+
+    /**
+     * @brief Sets up spdlog loggers for each channel. Should be called once before using any loggers.
+     * Simulates the `util::LogService::init(config)` call
+     */
+    static void
+    init();
 
 protected:
     std::string
```
Comment (godexsoft) [inline tests/common/util/LoggerFixtures.hpp:48]: nit: This probably should be nodiscard

**Review by godexsoft — CHANGES_REQUESTED** [review]
Leaving some nits. Overall looks good 👍 
Not too sure about having `public virtual` everywhere - most places don't need it. But it's not a blocker.

File: src/util/log/Logger.cpp (hunk 4 above)
Comment (mathbunnyru) [reply src/util/log/Logger.cpp:382]: we can't do it, because all loggers will be destroyed

File: src/util/log/Logger.cpp (hunk 2 above)
Comment (mathbunnyru) [reply src/util/log/Logger.cpp:59]: agreed not to rename

File: src/util/log/Logger.cpp (hunk 3 above)
Comment (mathbunnyru) [reply src/util/log/Logger.cpp]: move initialized to state, and used it, thanks 👍

File: src/util/log/Logger.hpp (hunk 5 above)
Comment (mathbunnyru) [reply src/util/log/Logger.hpp:293]: mostly, it's not needed, so won't add here

File: tests/common/util/LoggerFixtures.hpp (hunk 6 above)
Comment (mathbunnyru) [reply tests/common/util/LoggerFixtures.hpp:48]: added

**Review by godexsoft — APPROVED** [review]
:rage2:
