### PR TITLE
fix: Support deleted object in ledger_entry

### LINKED ISSUE #1306: Support deleted object in `ledger_entry`
## Summary

Modifying the `ledger_entry` API as follows:

### New Request Parameter
| Field Name           | Type    | Description |
|--------------------- |:-------:| ------------|
| `include_deleted`       | ️boolean   |  _(Optional)_ If set to true and the queried object has been deleted, return its complete data prior to its deletion. If set to false or not provided and the queried object has been deleted, return `objectNotFound` (current behavior) .|

### New Response Parameter
| Field Name           | Type    | Description |
|--------------------- |:-------:| ------------|
| `deleted_ledger_index`       |number   |  _(Optional)_ Indicates the ledger index at which the object was deleted. 

## Motivation

Currently,  `ledger_entry`  API returns `objectNotFound` if the object has been deleted. But perhaps someone may want to find the object data before its deletion, without the need to dig through transaction history to find the index at which this particular object was deleted.

I think clio can introduce an improved `ledger_entry`  API with the a change - rather than returning `objectNotFound` for a deleted object, it would return the complete object data prior to its deletion, as well as an additional field to indicated the ledger index at which the object wad deleted. 

This is useful it  for something like XRPL explorer. For example, if I create a MPT page that queries `ledger_entry`, it would work fine as long as the MPT is not destroyed. However, after the MPT is destroyed, the MPT page will no longer be available because `ledger_entry` will now return `objectNotFound`. This would result in suboptimal experience in the explorer. This would improve the user experience on explorers in the long term, as explorer adds new page for each object type.

### PR DESCRIPTION
**Pull request by Kassaking7**
Fixes #1306

### CODE REVIEW

File: src/rpc/handlers/LedgerEntry.hpp [hunk 1]
```diff
@@ -101,6 +102,7 @@ class LedgerEntryHandler {
         std::optional<uint32_t> chainClaimId;
         std::optional<uint32_t> createAccountClaimId;
         std::optional<ripple::uint256> oracleNode;
+        std::optional<bool> include_deleted;
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.hpp]: 1 Maybe we can use bool directly? False by default? 
 2 Name convention: includeDeleted

File: src/rpc/handlers/LedgerEntry.hpp [hunk 2]
```diff
@@ -70,6 +70,7 @@ class LedgerEntryHandler {
         std::optional<boost::json::object> node;
         std::optional<std::string> nodeBinary;
         bool validated = true;
+        std::optional<uint32_t> deleted_ledger_index;
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.hpp]: Our established name convention  : deletedLedgerIndex

File: src/data/BackendInterface.hpp [hunk 3]
```diff
@@ -378,6 +378,29 @@ class BackendInterface {
     std::optional<Blob>
     fetchLedgerObject(ripple::uint256 const& key, std::uint32_t sequence, boost::asio::yield_context yield) const;
 
+    /**
+     * @brief Fetches Last two ledger objects.
```
Comment (cindyyan317) [inline src/data/BackendInterface.hpp]: Last -> last

File: src/data/BackendInterface.hpp [hunk 4]
```diff
@@ -378,6 +378,29 @@ class BackendInterface {
...
+     *
+     *
+     * @param key The key of the object
+     * @param sequence The ledger sequence to fetch for
+     * @param yield The coroutine context
+     * @return A vector containing two Blobs, representing last two ledger objects
```
Comment (cindyyan317) [inline src/data/BackendInterface.hpp]: Maybe we can put more detail here.

**Review by cindyyan317 — CHANGES_REQUESTED** [review]
Since the **include_deleted** is optional, I would suggest to try to utilize our cache as much as possible. Maybe we don't need to land on DB every time.

1 Keep using 'fetchLedgerObject' to get the  last object by seq (This method will use cache effectively)
2 If **include_deleted** is true and the object from 1 is empty , use **fetchLedgerObject** + the seq_from_object_1 -1 getting the second one.
I think it might be easier and no need extra CQL statement.  I am happy to discuss it offline if needed.
 
BTW, please assign the issue to yourself when you start doing that. In case other people may pick it as no one works on it.

File: src/data/BackendInterface.cpp [hunk 5]
```diff
@@ -103,6 +103,7 @@ BackendInterface::fetchLedgerObject(
     return dbObj;
 }
 
+
```
Comment (godexsoft) [inline src/data/BackendInterface.cpp:117]: Extra space line is not needed here

File: src/rpc/handlers/LedgerEntry.cpp [hunk 6]
```diff
@@ -157,21 +157,29 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
     auto const lgrInfo = std::get<ripple::LedgerHeader>(lgrInfoOrStatus);
-    auto const ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
-
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
-
+    std::optional<data::Blob> ledgerObject;
+    auto output = LedgerEntryHandler::Output{};
+    output.deletedLedgerIndex = std::nullopt;
+    ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp]: `auto ledgerObject` here is fine, no need to create an empty optional first just to overwrite it two lines down 👍 
And then let's add a line of space between this and the if.
We also usually don't add curly braces for one line `if`s.

File: src/rpc/handlers/LedgerEntry.cpp [hunk 7]
```diff
@@ -157,21 +157,29 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
+    if (!ledgerObject || ledgerObject->empty()) {
+        if (input.includeDeleted == false) {
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp]: Another nit: `if (not input.includeDeleted)` reads better and is shorter. 
When it's possible to make code read like plain English it is usually better to go for it

File: src/data/BackendInterface.hpp [hunk 8]
```diff
@@ -377,7 +377,7 @@ class BackendInterface {
      */
     std::optional<Blob>
     fetchLedgerObject(ripple::uint256 const& key, std::uint32_t sequence, boost::asio::yield_context yield) const;
-
+
```
Comment (godexsoft) [inline src/data/BackendInterface.hpp]: I'm surprised clang-format is not screaming at this.. let's remove unnecessary whitespace leaving only `\n` as before

File: src/rpc/handlers/LedgerEntry.cpp [hunk 9]
```diff
@@ -157,21 +157,29 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
     ripple::STLedgerEntry const sle{ripple::SerialIter{ledgerObject->data(), ledgerObject->size()}, key};
 
     if (input.expectedType != ripple::ltANY && sle.getType() != input.expectedType)
         return Error{Status{"unexpectedLedgerType"}};
 
-    auto output = LedgerEntryHandler::Output{};
     output.index = ripple::strHex(key);
     output.ledgerIndex = lgrInfo.seq;
     output.ledgerHash = ripple::strHex(lgrInfo.hash);
-
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp]: Please don't remove spaces that make sense - they separate blocks of variables from `if`s, unrelated `if`s from each other, etc. - let's add them back and also add some more around your 'if' statements 👍

File: src/rpc/handlers/LedgerEntry.hpp [hunk 10]
```diff
@@ -101,6 +102,7 @@ class LedgerEntryHandler {
         std::optional<uint32_t> chainClaimId;
         std::optional<uint32_t> createAccountClaimId;
         std::optional<ripple::uint256> oracleNode;
+        bool includeDeleted;
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.hpp]: Let's add `= false;`

File: src/rpc/handlers/LedgerEntry.hpp [hunk 11]
```diff
@@ -70,6 +70,7 @@ class LedgerEntryHandler {
         std::optional<boost::json::object> node;
         std::optional<std::string> nodeBinary;
         bool validated = true;
+        std::optional<uint32_t> deletedLedgerIndex;
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.hpp:74]: let's keep `validated` at the bottom of the struct as it was before 👍

File: tests/unit/rpc/handlers/LedgerEntryTests.cpp [hunk 12]
```diff
@@ -2612,3 +2614,239 @@ TEST(RPCLedgerEntrySpecTest, DeprecatedFields)
     EXPECT_EQ(warning.at("id").as_int64(), static_cast<int64_t>(rpc::WarningCode::warnRPC_DEPRECATED));
     EXPECT_NE(warning.at("message").as_string().find("Field 'ledger' is deprecated."), std::string::npos) << warning;
 }
+
+// Same as BinaryFalse with include_deleted set to true
+// Expected Result: same as BinaryFalse
+TEST_F(RPCLedgerEntryTest, BinaryFalseIncludeDeleted)
+{
+    static auto constexpr OUT = R"({
+        "ledger_hash":"4BC50C9B0D8515D3EAAE1E74B29A95804346C491EE1A95BF25E4AAB854A6A652",
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/LedgerEntryTests.cpp]: I'd appreciate if you format the json a bit more by adding spaces between `:` and values. I know not all jsons in our tests are already formatted correctly - "thanks" to everyone using copilot 😢 
But let's try not to add more to the mess 😃

File: tests/unit/rpc/handlers/LedgerEntryTests.cpp [hunk 13]
```diff
@@ -2612,3 +2614,239 @@ TEST(RPCLedgerEntrySpecTest, DeprecatedFields)
...
+                "index": "{}",
+                "include_deleted": true
+            }})",
+            INDEX1
+        ));
+        auto const output = handler.process(req, Context{yield});
+        ASSERT_TRUE(output);
+        EXPECT_EQ(*output.result, json::parse(OUT));
+    });
+}
```
Comment (godexsoft) [inline tests/unit/rpc/handlers/LedgerEntryTests.cpp]: Ah, classic. Please configure your IDE to automatically insert last empty line on save 👍

**Review by godexsoft — CHANGES_REQUESTED** [review]
Leaving a few nits 👍

File: src/rpc/handlers/LedgerEntry.cpp [hunk 14]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
         return Error{*status};
 
     auto const lgrInfo = std::get<ripple::LedgerHeader>(lgrInfoOrStatus);
-    auto const ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
-
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
+    auto output = LedgerEntryHandler::Output{};
+    output.deletedLedgerIndex = std::nullopt;
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp]: This line is redundant - the line above already creates `Output` with a `nullopt` for this field via `optional`'s default constructor.

File: src/rpc/handlers/LedgerEntry.cpp [hunk 15]
```diff
@@ -215,6 +222,9 @@ tag_invoke(boost::json::value_from_tag, boost::json::value& jv, LedgerEntryHandl
         {JS(index), output.index},
     };
 
+    if (output.deletedLedgerIndex) {
+        object["deleted_ledger_index"] = *(output.deletedLedgerIndex);
+    }
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp]: I'd add a line of space below this block and perhaps remove the curlies for this one line `if` 👍

File: src/rpc/handlers/LedgerEntry.cpp [hunk 16]
```diff
@@ -332,6 +342,8 @@ tag_invoke(boost::json::value_to_tag<LedgerEntryHandler::Input>, boost::json::va
         input.oracleNode = parseOracleFromJson(jv.at(JS(oracle)));
     }
 
+    if (jsonObject.contains("include_deleted"))
+        input.includeDeleted = jv.at("include_deleted").as_bool();
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.cpp:353]: I'd separate the final return from the `if` by a line of space.

File: src/rpc/handlers/LedgerEntry.hpp [hunk 17]
```diff
@@ -302,6 +304,7 @@ class LedgerEntryHandler {
                   meta::WithCustomError{modifiers::ToNumber{}, Status(ClioError::rpcMALFORMED_ORACLE_DOCUMENT_ID)}},
              }}},
             {JS(ledger), check::Deprecated{}},
+            {"include_deleted", validation::Type<bool>{}},
```
Comment (godexsoft) [inline src/rpc/handlers/LedgerEntry.hpp:319]: I assume you checked and there is no `JS(include_deleted)` but thought i'd ask ❓

**Review by godexsoft — CHANGES_REQUESTED** [review]
Found a few more small improvements. This PR looks very close though - great job 🙇

File: src/rpc/handlers/LedgerEntry.cpp [hunk 18]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
         return Error{*status};
 
     auto const lgrInfo = std::get<ripple::LedgerHeader>(lgrInfoOrStatus);
-    auto const ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
-
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
+    auto output = LedgerEntryHandler::Output{};
+    output.deletedLedgerIndex = std::nullopt;
+    auto ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp:166]: const?

File: src/rpc/handlers/LedgerEntry.cpp [hunk 19]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
+
+    if (!ledgerObject || ledgerObject->empty()) {
+        if (not input.includeDeleted) 
+            return Error{Status{"entryNotFound"}};
+        ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq - 1, ctx.yield);
+        if (!ledgerObject || ledgerObject->empty())
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp:168]: If an object is deleted at seq, it must exist for seq-1, right? We can use an ASSERT here.

File: src/rpc/handlers/LedgerEntry.cpp [hunk 20]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
+    auto output = LedgerEntryHandler::Output{};
+    output.deletedLedgerIndex = std::nullopt;
+    auto ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
+
+    if (!ledgerObject || ledgerObject->empty()) {
+        if (not input.includeDeleted) 
+            return Error{Status{"entryNotFound"}};
+        ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq - 1, ctx.yield);
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp]: lgrInfo.seq is the seq specified by the input, right? It is not the seq for the ledgerObject.

for example if object A got deleted at seq 100 but created at seq 80
in db, objects table is like:
key 100 null
key 80 0x1234
If the seq from input request is 120: 
First, we got the null as ledgerObject
Second, we shall use fetchLedgerObject(key,**99**, ctx.yield); to get 0x1234. If we use lgrInfo.seq - 1 which is 119, we will still get null, right?

**Review by cindyyan317 — CHANGES_REQUESTED** [review]
I think the seq you are using to query the second latest object is not right. You need the seq which the object is modified at.
You can find more info about 'objects' table from [here](https://github.com/XRPLF/clio/blob/b2eacf9868fa1005cec0dc010416cf611de36835/src/data/README.md#objects)

File: src/rpc/handlers/LedgerEntry.cpp (hunk 18 above)
Comment (godexsoft) [reply src/rpc/handlers/LedgerEntry.cpp:166]: `ledgerObject` is modified again below. But maybe there is no need to do that and it would be ok to just create a new variable in the loop, maybe hide it like `if (auto const ledgerObject = ...; !ledgerObject.isEmpty() or ...)`.

**Comment by Kassaking7** [comment]
I give a change on the logic:
1. Try to fetch the object with a given sequence
2. If failed, it means the sequence it deleted is at least <= current given sequence
3. Use a new created function to fetch the sequence that the object deleted (no need for new CQL statement)
4. Use the new sequence-1 to fetch the latest object that is not deleted

Hope this time it works good :) I created a unit test for this case and looks good to me.

File: src/rpc/handlers/LedgerEntry.cpp [hunk 21]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
-
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
+    auto output = LedgerEntryHandler::Output{};
+    auto ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
+
+    if (!ledgerObject || ledgerObject->empty()) {
+        if (not input.includeDeleted) 
+            return Error{Status{"entryNotFound"}};
+        auto deleted_seq = sharedPtrBackend_->fetchLedgerObjectSeq(key, lgrInfo.seq, ctx.yield);
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp]: const ,name should be deletedSeq

**Review by cindyyan317 — COMMENTED** [review]
Nice work! Thanks 🙇 
Just some nits to fix, then we are ready to go

File: src/rpc/handlers/LedgerEntry.hpp (hunk 17 above)
Comment (Kassaking7) [reply src/rpc/handlers/LedgerEntry.hpp:319]: Yes there's no JS(include_deleted)

File: src/rpc/handlers/LedgerEntry.cpp [hunk 22]
```diff
@@ -157,17 +157,24 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
-
-    if (!ledgerObject || ledgerObject->empty())
-        return Error{Status{"entryNotFound"}};
+    auto output = LedgerEntryHandler::Output{};
+    auto ledgerObject = sharedPtrBackend_->fetchLedgerObject(key, lgrInfo.seq, ctx.yield);
+
+    if (!ledgerObject || ledgerObject->empty()) {
+        if (not input.includeDeleted) 
+            return Error{Status{"entryNotFound"}};
+        auto const deletedSeq = sharedPtrBackend_->fetchLedgerObjectSeq(key, lgrInfo.seq, ctx.yield);
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp:171]: Do we need to check deletedSeq, it can be nullopt?

File: src/rpc/handlers/LedgerEntry.cpp [hunk 23]
```diff
@@ -157,17 +157,26 @@ LedgerEntryHandler::process(LedgerEntryHandler::Input input, Context const& ctx)
...
+        if (!deletedSeq) 
+            return Error{Status{"entrySeqNotFound"}};
```
Comment (cindyyan317) [inline src/rpc/handlers/LedgerEntry.cpp]: Should also be entryNotFound, right?

**Review by cindyyan317 — DISMISSED** [review]
LGTM

File: src/data/BackendInterface.hpp [hunk 24]
```diff
@@ -407,6 +420,17 @@ class BackendInterface {
     virtual std::optional<Blob>
     doFetchLedgerObject(ripple::uint256 const& key, std::uint32_t sequence, boost::asio::yield_context yield) const = 0;
 
+    /**
+     * @brief The database-specific implementation for fetching a ledger object sequence.
+     *
+     * @param key The key to fetch for
+     * @param sequence The ledger sequence to fetch for
+     * @param yield The coroutine context
+     * @return The object as a sequence on success; nullopt otherwise
```
Comment (godexsoft) [inline src/data/BackendInterface.hpp]: Confusing a bit: i think this returns the sequence if available, not an object as a sequence

File: src/data/CassandraBackend.hpp [hunk 25]
```diff
@@ -567,6 +567,24 @@ class BasicCassandraBackend : public BackendInterface {
         return std::nullopt;
     }
 
+    std::optional<std::uint32_t>
+    doFetchLedgerObjectSeq(ripple::uint256 const& key, std::uint32_t const sequence, boost::asio::yield_context yield)
+        const override
+    {
+        LOG(log_.debug()) << "Fetching ledger object for seq " << sequence << ", key = " << ripple::to_string(key);
+        if (auto const res = executor_.read(yield, schema_->selectObject, key, sequence); res) {
+            if (auto const result = res->template get<std::uint32_t>(); result) {
```
Comment (godexsoft) [inline src/data/CassandraBackend.hpp]: I'm not sure how this works, you are trying to read a Blob as a uint32_t. Is that allowed and what was meant?

Comment (cindyyan317) [reply src/data/CassandraBackend.hpp]: It is true. it gets by order.

Comment (godexsoft) [reply src/data/CassandraBackend.hpp]: You need to either `auto [seq, _] = get<Blob, uint32_t>` and discard the blob or add a `get<T>(std::size_t position)` and use that instead (in `data/cassandra/impl/Result.hpp`).

**Comment by Kassaking7** [comment]
Gave a test on it with real DB and it works good on my side:
1. Do ledger_accept 300 times
2. Create 2 users
3. Mint a NFT
4. Create a offer with that NFT id
5. Record that offer id and cancel it (now in DB the corresponding object is 0x, sequence is 307)
6. Create another 2 users so current sequence is far beyond the deleted sequence
7. Call ledger_entry with include_deleted true and return deleted_ledger_index 307

File: tests/unit/rpc/handlers/LedgerEntryTests.cpp [hunk 26]
```diff
@@ -2620,3 +2622,321 @@ TEST(RPCLedgerEntrySpecTest, DeprecatedFields)
...
+
+// Test for object seq not exist in database
+// Expected Result: return entrySeqNotFound error
```
Comment (cindyyan317) [inline tests/unit/rpc/handlers/LedgerEntryTests.cpp]: Nice to add it. But the comment look off. Should be entryNotFound?

**Review by cindyyan317 — DISMISSED** [review]
Good job!

**Review by cindyyan317 — APPROVED** [review]

**Review by godexsoft — APPROVED** [review]
Looks fine now 👍 🚀
