### PR TITLE
fix: deletion script will not OOM

### LINKED ISSUE #1676: Fix Deletion Script OOM
## Summary
Deletion script currently stores all queries in memory before executing them, resulting in OOM if we delete millions of ledgers at a time. We should prevent this. Also good idea to add a file to support resume deletion from where it had left off in case of the program crashing

### PR DESCRIPTION
**Pull request by PeterChen13579**
fixes #1676 and #1678

### CODE REVIEW

File: tools/cassandra_delete_range/cassandra_delete_range.go [hunk 1]
```diff
@@ -208,3 +225,92 @@ func prepareDb(dbHosts *string) (*gocql.ClusterConfig, error) {
...
+			start, err1 := strconv.ParseInt(startStr, 10, 64)
+			end, err2 := strconv.ParseInt(endStr, 10, 64)
+
+			if err1 != nil || err2 != nil {
+				log.Fatalf("Error converting integer: %s, %s", err1, err2)
+			}
+			rangeRead[start] = end
+		}
+		ledgerOrTokenRange = &util.StoredRange{}
+		ledgerOrTokenRange.TokenRange = maybe.Set(rangeRead)
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/cassandra_delete_range.go]: Does TokenRange need to be Maybe?

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 2]
```diff
@@ -308,54 +410,167 @@ func (c *ClioCass) prepareSimpleDeleteQueries(
...
+				atomic.AddUint64(&totalErrors, err)
+				info = deleteInfo{Query: deleteQueryTemplate}
+			}
+		}
+		// delete the rest of queries if exists
+		if len(info.Data) > 0 {
+			_, err := c.performDeleteQueries(&info, session, colSettings)
+			atomic.AddUint64(&totalDeletes, uint64(len(info.Data)))
+			atomic.AddUint64(&totalErrors, err)
+			info = deleteInfo{Query: deleteQueryTemplate}
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: No need to reset here

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 3]
```diff
@@ -180,100 +189,193 @@ func (c *ClioCass) pruneData(
...
+		}
+		fmt.Fprintf(file, "%s\n", c.settings.Command)
+		file.WriteString("diff\n")
+
 		log.Println("Generating delete queries for diff table")
-		info = c.prepareSimpleDeleteQueries(rangeFrom, rangeTo,
-			"DELETE FROM diff WHERE seq = ?")
-		log.Printf("Total delete queries: %d\n\n", len(info.Data))
-		deleteCount, errCount = c.performDeleteQueries(&info, columnSettings{UseBlob: false, UseSeq: true})
+		deleteCount, errCount = c.prepareSimpleDeleteQueries(rangeFrom, rangeTo,
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: Maybe consider rename this function. It is not only "prepare" anymore.

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 4]
```diff
@@ -368,70 +583,78 @@ func (c *ClioCass) prepareDeleteQueries(
...
-								atomic.AddUint64(&totalErrors, 1)
-							}
+						if !prepareDeleteResult {
+							log.Printf("ERROR: page iteration failed: %s\n", err)
+							fmt.Fprintf(os.Stderr, "FAILED QUERY: %s\n", fmt.Sprintf("%s [from=%d][to=%d][pagestate=%x]", queryTemplate, r.StartRange, r.EndRange, pageState))
+							atomic.AddUint64(&totalErrors, 1)
 						}
 
 						if len(nextPageState) == 0 {
+							// Checks for delete queries every page
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: When nextPageState is 0, we have iterated all pages for this query. So this comment looks off here.

File: tools/cassandra_delete_range/cassandra_delete_range.go [hunk 5]
```diff
@@ -208,3 +225,92 @@ func prepareDb(dbHosts *string) (*gocql.ClusterConfig, error) {
...
+		fallthrough
+	case "transactions":
+		*skipLedgerHashesTable = true
+		fallthrough
+	case "ledger_hashes":
+		*skipObjectsTable = true
+		fallthrough
+	case "objects":
+		*skipSuccessorTable = true
+	}
```
Comment (kuznetsss) [inline tools/cassandra_delete_range/cassandra_delete_range.go]: What if none of these matched?

File: tools/cassandra_delete_range/cassandra_delete_range.go [hunk 6]
```diff
@@ -208,3 +225,92 @@ func prepareDb(dbHosts *string) (*gocql.ClusterConfig, error) {
...
+
+	scanner.Scan()
+	if scanner.Text() == "token_range" {
+		rangeRead := make(map[int64]int64)
+
+		// now go through all the ledger range and load it to a set
+		for scanner.Scan() {
+			line := scanner.Text()
+			Range := strings.Split(line, ",")
```
Comment (kuznetsss) [inline tools/cassandra_delete_range/cassandra_delete_range.go]:
```suggestion
			range := strings.Split(line, ",")
```

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 7]
```diff
@@ -368,70 +583,78 @@ func (c *ClioCass) prepareDeleteQueries(
...
+					if c.settings.RangesRead != nil {
+						if c.settings.RangesRead.TokenRange.HasValue() {
+							if value, exists := c.settings.RangesRead.TokenRange.Value()[r.StartRange]; exists {
+								// Check for end range
+								if value == r.EndRange {
+									continue
+								}
+							}
+						} else {
+							log.Fatal("token_range should exist in continue.txt")
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: The last run could be terminated when the first slice is processing. So we can not error out here. If the map is empty, we  just do nothing.

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 8]
```diff
@@ -308,54 +410,167 @@ func (c *ClioCass) prepareSimpleDeleteQueries(
...
+			if keepLastValid && !slices.Equal(previousKey, key) {
+				previousKey = key
+				foundLastValid = false
+			}
+
+			// only grab the rows that are in the correct range of sequence numbers
+			if fromLedgerIdx.HasValue() && fromLedgerIdx.Value() <= seq {
+				info.Data = append(info.Data, deleteParams{Seq: seq, Blob: key})
+			} else if toLedgerIdx.HasValue() {
+				if seq <= toLedgerIdx.Value() && (!keepLastValid || foundLastValid) {
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go:503]: I saw you changed the "<" to "<=". Is it for bug fixing?

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 9]
```diff
@@ -180,100 +189,193 @@ func (c *ClioCass) pruneData(
 
 	// successor queries
 	if !c.settings.SkipSuccessorTable {
+		file, err := os.Create("continue.txt")
+		if err != nil {
+			fmt.Println("Error creating file in Successor table:", err)
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: Maybe the error should be "Error creating file for successor"?

File: tools/cassandra_delete_range/internal/cass/cass.go [hunk 10]
```diff
@@ -180,100 +189,193 @@ func (c *ClioCass) pruneData(
 
 	// successor queries
 	if !c.settings.SkipSuccessorTable {
+		file, err := os.Create("continue.txt")
```
Comment (cindyyan317) [inline tools/cassandra_delete_range/internal/cass/cass.go]: We might be able to tidy up all logic about "continue.txt" to a class. Then you can get rid of hardcoded file name and repeated logic. You can also leverage the object scope to manage the file creation and deletion.

**Review by cindyyan317 — CHANGES_REQUESTED** [review]
The logic looks good to me. 
But the bookmark can be put into a class. 
The workerCount seems incorrec. If I understand correctly, the number of goroutine running concurrently is workerCount*workerCount now.

File: tools/cassandra_delete_range/internal/cass/cass.go (hunk 8 above)
Comment (PeterChen13579) [reply tools/cassandra_delete_range/internal/cass/cass.go:503]: Yes, in the initial script, I tested and there was a 1 off bug. (so if i delete before 100, it doesn't delete 99). This is because we already did -1 [here](https://github.com/XRPLF/clio/blob/2c18fd5465cfc3139a390a7ac834efdd803f9bcc/tools/cassandra_delete_range/internal/cass/cass.go#L80) so It has to be "<="

File: tools/cassandra_delete_range/cassandra_delete_range.go (hunk 6 above)
Comment (PeterChen13579) [reply tools/cassandra_delete_range/cassandra_delete_range.go]: I think range is a special key word in Go, so it can't be used to declare variables. I'll rename it to tokenRange instead to obey the naming convention 👍

File: tools/cassandra_delete_range/cassandra_delete_range.go (hunk 5 above)
Comment (PeterChen13579) [reply tools/cassandra_delete_range/cassandra_delete_range.go]: Nothing will happen. Now thinking about it, it'll be a good idea to handle such case because at least one of the cases should match

**Comment by cindyyan317** [comment]
Maybe we can pack the continue.txt logic all in one class like:
```
type Marker struct {
	cmd  string
	file *os.File
}

func NewMarker(cmd string) *Marker {
	return &Marker{cmd: cmd}
}

func CloseMarker(m *Marker) {
	if m.file != nil {
		m.file.Close()
	}
	os.Remove("continue.txt")
}

func (m *Marker) EnterTable(table string) error {
	// Create the file
	file, err := os.OpenFile("continue.txt", os.O_WRONLY|os.O_TRUNC, 0644)
	m.file = file
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	fmt.Fprintf(m.file, "%s\n", m.cmd)
	m.file.WriteString(fmt.Sprintf("%s\n", table))
	return nil
}

func (m *Marker) MarkProgress(x int64, y int64) {
	fmt.Fprintf(m.file, "%d, %d \n", x, y)
}

func (m *Marker) ExitTable() {
	m.file.Close()
	m.file = nil
}

```

**Comment by PeterChen13579** [comment]
oh yea, this way is definitely better

> Maybe we can pack the continue.txt logic all in one class like:
> 
> ```
> type Marker struct {
> 	cmd  string
> 	file *os.File
> }
> 
> func NewMarker(cmd string) *Marker {
> 	return &Marker{cmd: cmd}
> }
> 
> func CloseMarker(m *Marker) {
> 	if m.file != nil {
> 		m.file.Close()
> 	}
> 	os.Remove("continue.txt")
> }
> 
> func (m *Marker) EnterTable(table string) error {
> 	// Create the file
> 	file, err := os.OpenFile("continue.txt", os.O_WRONLY|os.O_TRUNC, 0644)
> 	m.file = file
> 	if err != nil {
> 		return fmt.Errorf("failed to create file: %w", err)
> 	}
> 	fmt.Fprintf(m.file, "%s\n", m.cmd)
> 	m.file.WriteString(fmt.Sprintf("%s\n", table))
> 	return nil
> }
> 
> func (m *Marker) MarkProgress(x int64, y int64) {
> 	fmt.Fprintf(m.file, "%d, %d \n", x, y)
> }
> 
> func (m *Marker) ExitTable() {
> 	m.file.Close()
> 	m.file = nil
> }
> ```

**Review by cindyyan317 — APPROVED** [review]
Thanks ~ LGTM
