### PR TITLE
Fix malformed output format over ws rpc

### LINKED ISSUE #405: Clio web socket responses have extra parameters than rippled.
Sample request:
`{"id": 2,"command": "account_info","account": "r4krwypySXzXN8avzGRJCMECUujm3VJsBp","strict": true,"ledger_index": "validated","queue": true}`

Rippled response:
`{"error":"invalidParams","error_code":31,"error_message":"Invalid parameters.","id":2,"ledger_hash":"CDF31686D81F672EF8CEEDDC852661FB1D7175F03EC6C83AE2580036B682B3D6","ledger_index":23502573,"request":{"account":"r4krwypySXzXN8avzGRJCMECUujm3VJsBp","command":"account_info","id":2,"ledger_index":"validated","queue":true,"strict":true},"status":"error","type":"response","validated":true}`

Clio response:
`{"id":2,"result":{"error":"invalidParams","error_code":31,"error_message":"Invalid parameters.","id":2,"ledger_hash":"FF9F73E897AC0BE2E919C9BB91142FBC64B2E8DAD78DB65B1C0C1DDC8233D4F9","ledger_index":23502582,"request":{"account":"r4krwypySXzXN8avzGRJCMECUujm3VJsBp","command":"account_info","id":2,"ledger_index":"validated","queue":true,"strict":true},"status":"error","type":"response","validated":true,"forwarded":true},"status":"success","type":"response","warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}`

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes #405 

When accessing `clio` thru ws rpc a forwarded rpc result is no longer wrapped in extra `result` object.
All fields are copied from the original `rippled` response when forwarding.

### CODE REVIEW

File: src/rpc/handlers/AccountInfo.cpp [hunk 1]
```diff
@@ -50,30 +50,19 @@ doAccountInfo(Context const& context)
     if (!accountID)
         return Status{RippledError::rpcACT_MALFORMED};
 
-    assert(accountID.has_value());
```
Comment (godexsoft) [inline src/rpc/handlers/AccountInfo.cpp:53]: It's always true here - removing because useless

File: src/rpc/RPC.cpp [hunk 2]
```diff
@@ -321,9 +321,6 @@ buildResponse(Context const& ctx)
         if (!res)
             return Status{RippledError::rpcFAILED_TO_FORWARD};
 
-        if (res->contains("result") && res->at("result").is_object())
-            return res->at("result").as_object();
-
```
Comment (cjcobb23) [inline src/rpc/RPC.cpp:326]: Why are we removing this?

**Review by cjcobb23 — COMMENTED** [review]
This looks good to me, but lets rerun the integration tests on this, just to be sure

File: src/rpc/RPC.cpp (hunk 2 above)
Comment (godexsoft) [reply src/rpc/RPC.cpp:326]: This moved into the `HttpBase` case only. This was removing any top-level fields from `rippled`s response which leads to losing fields in some cases.

**Review by legleux — APPROVED** [review]
:shipit:
