### PR TITLE
fix: AccountNFT with invalid marker

### LINKED ISSUE #1497: "account_nfts" with unassociated marker is returning empty account_nfts instead of error.
## Issue Description

"account_nfts" with unassociated marker(i.e., marker from another method "account_channels") is not returning error.

Not sure if the response should error out or return empty account_nfts. As rippled is fixing the issue, will have to replicate it in Clio.

## Steps to Reproduce

Sample request:
`{
  "method": "account_nfts",
  "params": [
    {
        "account":"ra1egD7jzyZWhcDaPD1eFPKzdSMVQCTsXM",
        "marker": "10394D3EA937A85A4482D2071412A33C8582A6EB4C3B7FD59C76012D83AC08C6"
    }
  ]
}`

## Expected Result

Current response matches with rippled. If there's a fix for [https://github.com/XRPLF/rippled/issues/4314](url) which returns error, Clio should replicate it.

## Actual Result

`{
    "result": {
        "ledger_hash": "41560CD72E0E9B68BC8D9A8E261695392C22B3E115E0796119DC40B28C26E242",
        "ledger_index": 1936194,
        "validated": true,
        "account": "ra1egD7jzyZWhcDaPD1eFPKzdSMVQCTsXM",
        "account_nfts": [],
        "limit": 100,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

### PR DESCRIPTION
**Pull request by PeterChen13579**
Fixes [#1497](https://github.com/XRPLF/clio/issues/1497)
Mimics the behavior of the [fix on Rippled side](https://github.com/XRPLF/rippled/pull/5045)

### CODE REVIEW

File: src/rpc/handlers/AccountNFTs.cpp [hunk 1]
```diff
@@ -78,8 +79,16 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
         input.marker ? ripple::uint256{input.marker->c_str()} : ripple::keylet::nftpage_max(*accountID).key;
     auto const blob = sharedPtrBackend_->fetchLedgerObject(pageKey, lgrInfo.seq, ctx.yield);
 
-    if (!blob)
+    bool pastMarker = !static_cast<bool>(input.marker);
```
Comment (godexsoft) [inline src/rpc/handlers/AccountNFTs.cpp]: `not input.marker.has_value()` reads better, wdyt?

File: src/rpc/handlers/AccountNFTs.cpp [hunk 2]
```diff
@@ -78,8 +79,16 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
...
+    bool markerFound = false;
+    bool const markerSet = input.marker.has_value();
```
Comment (godexsoft) [inline src/rpc/handlers/AccountNFTs.cpp]: can use `auto` here and above

File: src/rpc/handlers/AccountNFTs.cpp (hunk 1 above)
Comment (cindyyan317) [inline src/rpc/handlers/AccountNFTs.cpp]: is it input.marker.has_value()?

**Review by godexsoft — CHANGES_REQUESTED** [review]
Nice, just a few nits 👍

File: src/rpc/handlers/AccountNFTs.cpp [hunk 3]
```diff
@@ -89,6 +98,25 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
...
+            auto const maskedNftokenID = nftokenID & ripple::nft::pageMask;
+
+            if (!pastMarker) {
+                if (maskedNftokenID < maskedMarker)
+                    continue;
+
+                if (maskedNftokenID == maskedMarker && nftokenID < pageKey)
+                    continue;
+
+                if (nftokenID == pageKey) {
```
Comment (cindyyan317) [inline src/rpc/handlers/AccountNFTs.cpp]: i understood that this part of code came from rippled's code. However, Clio's implementation is slightly different.
In rippled, the marker is the nft id, however in Clio, the marker is page id. 
So it doesn't make sense to compare nfttokenId with pageKey here. 
The 'limit' works differently. for rippled, limit is the number of nftokens, for clio is the page number. According to the document , It should be page number.

**Review by cindyyan317 — CHANGES_REQUESTED** [review]
Good stuff 👍 

I think the marker is different in Clio, comparing with rippled. So rippled's approach might not work on Clio. 
Also please check the document https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/account-methods/account_nfts#account_nfts, I think Clio's limit is also different.

**Comment by shawnxie999** [comment]
@cindyyan317 rippled can directly fetch a page based on the NFTokenID marker. But clio can't do this, it has to traverse from the last page. So I assume that's why the marker is the ID of the page itself. I think we can still try to return a NFTokenID as a marker, but it would require clio to traverse from the last token page everytime a marker is provided, which would make the API less efficient

File: src/rpc/handlers/AccountNFTs.cpp (hunk 2 above)
Comment (kuznetsss) [reply src/rpc/handlers/AccountNFTs.cpp]: I would say `bool` is completely fine and maybe for the line 84 is even better than `auto`.

Comment (godexsoft) [reply src/rpc/handlers/AccountNFTs.cpp]: i don't mind either way. my preference would be `auto` though.

**Comment by cindyyan317** [comment]
> @cindyyan317 rippled can directly fetch a page based on the NFTokenID marker. But clio can't do this, it has to traverse from the last page. So I assume that's why the marker is the ID of the page itself. I think we can still try to return a NFTokenID as a marker, but it would require clio to traverse from the last token page everytime a marker is provided, which would make the API less efficient

@shawnxie999 Thanks for the suggestion. According to the [doc](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/account-methods/account_nfts#account_nfts) , the marker should be page id. We will flag this mismatch to rippled and discuss the correct fix.

For this PR, I think we don't mimic rippled. The marker is considered valid if it is a valid page object of account .

File: tests/unit/rpc/handlers/AccountNFTsTests.cpp [hunk 4]
```diff
@@ -402,6 +403,42 @@ TEST_F(RPCAccountNFTsHandlerTest, Marker)
...
+    auto const ledgerHeader = CreateLedgerHeader(LEDGERHASH, MAXSEQ);
+    EXPECT_CALL(*backend, fetchLedgerBySequence).Times(1);
+    ON_CALL(*backend, fetchLedgerBySequence).WillByDefault(Return(ledgerHeader));
+
+    auto const accountObject = CreateAccountRootObject(ACCOUNT, 0, 1, 10, 2, TXNID, 3);
+    auto const accountID = GetAccountIDWithString(ACCOUNT);
+    ON_CALL(*backend, doFetchLedgerObject(ripple::keylet::account(accountID).key, 30, _))
+        .WillByDefault(Return(accountObject.getSerializer().peekData()));
+
+    auto const pageObject =
```
Comment (cindyyan317) [inline tests/unit/rpc/handlers/AccountNFTsTests.cpp:474]: I think when marker is invalid, handler will return error. These mock will not be used.

File: src/rpc/handlers/AccountNFTs.cpp [hunk 5]
```diff
@@ -79,7 +79,7 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
     auto const blob = sharedPtrBackend_->fetchLedgerObject(pageKey, lgrInfo.seq, ctx.yield);
 
     if (!blob)
```
Comment (cindyyan317) [inline src/rpc/handlers/AccountNFTs.cpp]: If the blob is empty or does not exist , maybe because this account does not have any NFT. In this case, the marker is not given, we should not return error. 
If the blob is not empty ,maybe its type is not NFT page. In this case, we should return error. So I think we need to check the type somewhere.

File: src/rpc/handlers/AccountNFTs.cpp [hunk 6]
```diff
@@ -77,11 +77,19 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
     auto const pageKey =
         input.marker ? ripple::uint256{input.marker->c_str()} : ripple::keylet::nftpage_max(*accountID).key;
     auto const blob = sharedPtrBackend_->fetchLedgerObject(pageKey, lgrInfo.seq, ctx.yield);
+    auto const markerSet = input.marker.has_value();
 
-    if (!blob)
+    if (!blob) {
+        if (markerSet)
```
Comment (cindyyan317) [inline src/rpc/handlers/AccountNFTs.cpp]: Since markerSet is used only inside the if, we may move 80 into if branch, or just use input.marker.has_value() here

File: src/rpc/handlers/AccountNFTs.cpp [hunk 7]
```diff
@@ -77,11 +77,19 @@ AccountNFTsHandler::process(AccountNFTsHandler::Input input, Context const& ctx)
...
+            return Error{Status{RippledError::rpcINVALID_PARAMS, "Marker field does not match any valid Page ID"}};
         return response;
+    }
 
     std::optional<ripple::SLE const> page{ripple::SLE{ripple::SerialIter{blob->data(), blob->size()}, pageKey}};
+
+    if (page->getType() != ripple::ltNFTOKEN_PAGE)
```
Comment (cindyyan317) [inline src/rpc/handlers/AccountNFTs.cpp:89]: Worth adding an unittest to cover this line.

**Review by cindyyan317 — APPROVED** [review]
LGTM

**Review by godexsoft — APPROVED** [review]
👍
