### PR TITLE
Fix ordering of output amounts

### LINKED ISSUE #1156: [amm_info] with two currency assets other than XRP case response of Clio differs from rippled.
`amount` and `amount2` is interchanges in Clio response

Request:
```json 
{
  "method": "amm_info",
  "params": [
    {
      "asset": {
        "currency": "USD",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "asset2": {
        "currency": "CNY",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "ledger_index": "validated",
      "Fee": "20"
    }
  ]
}
```  

Rippled response:
```json 
{
  "result": {
    "amm": {
      "account": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
      "amount": {
        "currency": "USD",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "amount2": {
        "currency": "CNY",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "asset2_frozen": False,
      "asset_frozen": False,
      "auction_slot": {
        "account": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "discounted_fee": 0,
        "expiration": "2024-02-03T22:52:31+0000",
        "price": {
          "currency": "03BD84B7AAC3AC30F8BFF6F9D8221069D277EB6E",
          "issuer": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
          "value": "0"
        },
        "time_interval": 0
      },
      "lp_token": {
        "currency": "03BD84B7AAC3AC30F8BFF6F9D8221069D277EB6E",
        "issuer": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
        "value": "10"
      },
      "trading_fee": 0,
      "vote_slots": [
        {
          "account": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
          "trading_fee": 0,
          "vote_weight": 100000
        }
      ]
    },
    "ledger_hash": "F6E62ED18BB3D39BF89CF645191164FB0B171D70ED6D121E8E44C85E34EBFC8C",
    "ledger_index": 3898311,
    "status": "success",
    "validated": True
  }
}
```  
Clio response:
```json 
{
  "result": {
    "amm": {
      "lp_token": {
        "currency": "03BD84B7AAC3AC30F8BFF6F9D8221069D277EB6E",
        "issuer": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
        "value": "10"
      },
      "amount": {
        "currency": "CNY",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "amount2": {
        "currency": "USD",
        "issuer": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "value": "10"
      },
      "account": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
      "trading_fee": 0,
      "auction_slot": {
        "time_interval": 0,
        "price": {
          "currency": "03BD84B7AAC3AC30F8BFF6F9D8221069D277EB6E",
          "issuer": "r4oqXF4oGNakpiFFKMoWX16uQkDKEjv3xP",
          "value": "0"
        },
        "discounted_fee": 0,
        "account": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
        "expiration": "2024-02-03T22:52:31+0000"
      },
      "vote_slots": [
        {
          "account": "rnNoxzrNk9UGC1ncKkSCz8QugyhG5tRHmN",
          "trading_fee": 0,
          "vote_weight": 100000
        }
      ],
      "asset_frozen": False,
      "asset2_frozen": False
    },
    "ledger_index": 3898311,
    "ledger_hash": "F6E62ED18BB3D39BF89CF645191164FB0B171D70ED6D121E8E44C85E34EBFC8C",
    "validated": True,
    "status": "success"
  },
  "warnings": [
    {
      "id": 2001,
      "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include "ledger_index":"current" in your request"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by godexsoft**
Fixes #1156 

Thanks to @gregtatcam for helping find the reason of mismatch.

### CODE REVIEW

File: src/rpc/handlers/AMMInfo.cpp [hunk 1]
```diff
@@ -103,6 +103,9 @@ AMMInfoHandler::process(AMMInfoHandler::Input input, Context const& ctx) const
 
     auto const lgrInfo = std::get<LedgerInfo>(lgrInfoOrStatus);
 
+    auto issue1 = input.issue1;
+    auto issue2 = input.issue2;
```
Comment (kuznetsss) [inline src/rpc/handlers/AMMInfo.cpp]: Maybe move them closer to the first usage?

Comment (godexsoft) [reply src/rpc/handlers/AMMInfo.cpp]: Yeah, not sure why i added them up there tbh. 👍

**Review by kuznetsss — APPROVED** [review]
👍
