### PR TITLE
fix: Array parsing in new config

### LINKED ISSUE #1870: New Config parses arrays incorrectly
## Issue Description

If a config array consists of objects and each object has an optional field, json config might be parsed incorrectly.

This happens because json flattening discards index of each object and pushes back each field into flatten array.

### PR DESCRIPTION
**Pull request by kuznetsss**
Fixes #1870.

### CODE REVIEW

File: src/util/newconfig/ConfigFileJson.cpp [hunk 1]
```diff
@@ -165,4 +181,97 @@ ConfigFileJson::flattenJson(boost::json::object const& obj, std::string const& p
...
+    array: [
+        { a: 1},
+        { b: 2}
+    ]
+}
+
+array.[].a
+array.[].b
+
+*/
```
Comment (kuznetsss) [inline src/util/newconfig/ConfigFileJson.cpp]: Forgot to delete 😄

File: src/util/newconfig/Array.cpp [hunk 2]
```diff
@@ -36,14 +36,21 @@ Array::Array(ConfigValue arg) : itemPattern_{std::move(arg)}
 {
 }
 
+std::string_view
+Array::prefix(std::string_view key)
+{
+    ASSERT(key.contains(".[]"), "Provided key is not an array key: {}", key);
+
+    return key.substr(0, key.rfind(".[]") + 3);
```
Comment (godexsoft) [inline src/util/newconfig/Array.cpp]: nit: I think i understand what 3 means here but perhaps it would be nice to extract this into some constant just above to make it more clear and avoid magic numbers.

File: src/util/newconfig/ConfigFileJson.cpp [hunk 3]
```diff
@@ -165,4 +181,97 @@ ConfigFileJson::flattenJson(boost::json::object const& obj, std::string const& p
...
+
+void
+ConfigFileJson::flattenJsonNonRecursive(boost::json::object const& jsonRootObject)
```
Comment (godexsoft) [inline src/util/newconfig/ConfigFileJson.cpp]: nit: If we don't need the original implementation anymore, perhaps this can be renamed to `flattenJson` 🔢

File: src/util/newconfig/ConfigFileJson.cpp [hunk 4]
```diff
@@ -165,4 +181,97 @@ ConfigFileJson::flattenJson(boost::json::object const& obj, std::string const& p
...
+        std::string prefix;
+        std::optional<size_t> arrayIndex = std::nullopt;
+    };
+
+    std::queue<Task> tasks;
+    tasks.push(Task{.object = jsonRootObject, .prefix = ""});
+
+    std::unordered_map<std::string, size_t> arraysSizes;
+
+    while (tasks.size() > 0) {
```
Comment (godexsoft) [inline src/util/newconfig/ConfigFileJson.cpp]: nit: Queue also provides `.empty()` which probably reads more like english (e.g. `not tasks.empty()`)

File: src/util/newconfig/Types.hpp [hunk 5]
```diff
@@ -52,9 +70,24 @@ getType()
...
+        return ConfigType::Null;
     } else {
         static_assert(util::Unsupported<Type>, "Wrong config type");
     }
 }
 
 }  // namespace util::config
+
+/** @cond */
+// Doxygen could not parse this
```
Comment (godexsoft) [inline src/util/newconfig/Types.hpp:104]: Doxygen is so sad :rage4:

File: tests/unit/util/newconfig/ConfigFileJsonTests.cpp [hunk 6]
```diff
@@ -0,0 +1,480 @@
+//------------------------------------------------------------------------------
+/*
+    This file is part of clio: https://github.com/XRPLF/clio
+    Copyright (c) 2024, the clio developers.
```
Comment (godexsoft) [inline tests/unit/util/newconfig/ConfigFileJsonTests.cpp:4]: 2025 👍

File: tests/unit/util/newconfig/ConfigValueTests.cpp [hunk 7]
```diff
@@ -105,14 +214,14 @@ TEST(ConfigValue, OneOfConstraint)
...
-TEST(ConfigValue, IpConstraint)
+TEST_F(ConstraintTest, IpConstraint)
 {
     auto ip = ConfigValue{ConfigType::String}.defaultValue("127.0.0.1").withConstraint(gValidateIp);
     EXPECT_FALSE(ip.setValue("http://127.0.0.1").has_value());
     EXPECT_FALSE(ip.setValue("http://127.0.0.1.com").has_value());
     auto const err = ip.setValue("123.44");
     EXPECT_TRUE(err.has_value());
-    EXPECT_EQ(err->error, "Ip is not a valid ip address");
+    EXPECT_EQ(err->error, "Unknown_key Ip is not a valid ip address");
```
Comment (godexsoft) [inline tests/unit/util/newconfig/ConfigValueTests.cpp:226]: nit: The final error message reads really strangely. `[something] Ip is not a valid ip address`. Maybe `The value of [something] is not a valid IP address` or similar is better?

File: tests/unit/util/newconfig/ConfigFileJsonTests.cpp (hunk 6 above)
Comment (godexsoft) [reply tests/unit/util/newconfig/ConfigFileJsonTests.cpp:4]: Up to you - i see now that this file was moved from another place.

**Review by godexsoft — CHANGES_REQUESTED** [review]
Leaving small suggestions. Overall looks great 👍 🚀

File: src/util/newconfig/Array.hpp [hunk 8]
```diff
@@ -46,6 +46,17 @@ class Array {
      */
     Array(ConfigValue arg);
 
+    /**
+     * @brief Extract array prefix from a key, For example for a key foo.[].bar the method will return foo.[]
+     * @note Provided key must contain '.[]'
+     * @warning Be carriful with string_view! Returned value is valid only while the key is valid
```
Comment (PeterChen13579) [inline src/util/newconfig/Array.hpp]: Be `careful` 😄

File: tests/unit/util/newconfig/ConfigFileJsonTests.cpp [hunk 9]
```diff
@@ -0,0 +1,480 @@
...
+#include <algorithm>
+#include <cstdint>
+#include <string>
+#include <unordered_map>
+#include <variant>
+
+using namespace util::config;
+
+namespace {
+constexpr auto kEPS = 1e-9;
```
Comment (PeterChen13579) [inline tests/unit/util/newconfig/ConfigFileJsonTests.cpp:41]: what does EPS mean?

**Review by PeterChen13579 — COMMENTED** [review]
Looks good!!!  🚀

File: src/util/newconfig/ConfigFileJson.cpp [hunk 10]
```diff
@@ -69,14 +74,17 @@ extractJsonValue(boost::json::value const& jsonValue)
     if (jsonValue.is_double()) {
         return jsonValue.as_double();
     }
+    if (jsonValue.is_null()) {
+        return NullType{};
+    }
     ASSERT(false, "Json is not of type int, uint, string, bool or double");
     std::unreachable();
```
Comment (cindyyan317) [inline src/util/newconfig/ConfigFileJson.cpp:81]: Not for this Pr, do we need `unreachable` here?

File: src/util/newconfig/ConfigFileJson.cpp [hunk 11]
```diff
@@ -69,14 +74,17 @@ extractJsonValue(boost::json::value const& jsonValue)
     if (jsonValue.is_double()) {
         return jsonValue.as_double();
     }
+    if (jsonValue.is_null()) {
+        return NullType{};
+    }
     ASSERT(false, "Json is not of type int, uint, string, bool or double");
```
Comment (cindyyan317) [inline src/util/newconfig/ConfigFileJson.cpp]: maybe add `null` here. "Json is not of type int, uint, string, bool, double or empty")

File: src/util/newconfig/ConfigFileJson.cpp (hunk 10 above)
Comment (kuznetsss) [reply src/util/newconfig/ConfigFileJson.cpp:81]: Yeah, because this method returns something. Without `unreachable` compiler is not happy that we don't return anything.

File: tests/unit/util/newconfig/ConfigFileJsonTests.cpp (hunk 9 above)
Comment (kuznetsss) [reply tests/unit/util/newconfig/ConfigFileJsonTests.cpp:41]: It is short for epsilon - a greek letter which is used in math as a minimal value to see a difference between values.
I don't mind renaming if needed.

File: tests/unit/util/newconfig/ConfigValueTests.cpp (hunk 7 above)
Comment (kuznetsss) [reply tests/unit/util/newconfig/ConfigValueTests.cpp:226]: I think it is out of the PR's scope, because such style of errors is currently used across 'newconfig` library, so changing it only here would make it worse. I will create a task for refactoring.

Comment (kuznetsss) [reply tests/unit/util/newconfig/ConfigValueTests.cpp:226]: Created #1886.

File: tests/unit/util/newconfig/ConfigFileJsonTests.cpp (hunk 9 above)
Comment (PeterChen13579) [reply tests/unit/util/newconfig/ConfigFileJsonTests.cpp:41]: Ah I see. EPS is fine.

**Review by PeterChen13579 — DISMISSED** [review]
LGTM

**Review by godexsoft — DISMISSED** [review]
🚀

**Review by godexsoft — APPROVED** [review]
